# Packages

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import math
from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings('ignore')

from dotenv import load_dotenv
load_dotenv()

True

In [3]:
dir = os.getenv('DIR')
os.getcwd()
os.chdir(dir)
path = os.getcwd()

In [3]:
# Downloading the data directly from the Kaggle Servers
# kagglehub.competition_download('march-machine-learning-mania-2026')

# Merging CSV Files

In [5]:
os.listdir(os.path.join(path,'data','raw'))

['Cities.csv',
 'Conferences.csv',
 'MConferenceTourneyGames.csv',
 'MGameCities.csv',
 'MMasseyOrdinals.csv',
 'MNCAATourneyCompactResults.csv',
 'MNCAATourneyDetailedResults.csv',
 'MNCAATourneySeedRoundSlots.csv',
 'MNCAATourneySeeds.csv',
 'MNCAATourneySlots.csv',
 'MRegularSeasonCompactResults.csv',
 'MRegularSeasonDetailedResults.csv',
 'MSeasons.csv',
 'MSecondaryTourneyCompactResults.csv',
 'MSecondaryTourneyTeams.csv',
 'MTeamCoaches.csv',
 'MTeamConferences.csv',
 'MTeams.csv',
 'MTeamSpellings.csv',
 'SampleSubmissionStage1.csv',
 'SampleSubmissionStage2.csv',
 'WConferenceTourneyGames.csv',
 'WGameCities.csv',
 'WNCAATourneyCompactResults.csv',
 'WNCAATourneyDetailedResults.csv',
 'WNCAATourneySeeds.csv',
 'WNCAATourneySlots.csv',
 'WRegularSeasonCompactResults.csv',
 'WRegularSeasonDetailedResults.csv',
 'WSeasons.csv',
 'WSecondaryTourneyCompactResults.csv',
 'WSecondaryTourneyTeams.csv',
 'WTeamConferences.csv',
 'WTeams.csv',
 'WTeamSpellings.csv']

## Merging Men and Women Files

In [3]:
# Teams

teams = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MTeams.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WTeams.csv')).assign(Gender='W')
    ]
)

In [4]:

teamconferences = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MTeamConferences.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WTeamConferences.csv')).assign(Gender='W')
    ]
)

In [5]:

ncaatourneyseeds = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MNCAATourneySeeds.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WNCAATourneySeeds.csv')).assign(Gender='W')
    ]
)

In [6]:

secondarytourneyteams = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MSecondaryTourneyTeams.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WSecondaryTourneyTeams.csv')).assign(Gender='W')
    ]
)

In [7]:

secondarytourneycompactresults = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MSecondaryTourneyCompactResults.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WSecondaryTourneyCompactResults.csv')).assign(Gender='W')
    ]
)

In [8]:

ncaatourneycompactresults = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MNCAATourneyCompactResults.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WNCAATourneyCompactResults.csv')).assign(Gender='W')
    ]
)

In [9]:
ncaatourneydetailedresults = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MNCAATourneyDetailedResults.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WNCAATourneyDetailedResults.csv')).assign(Gender='W')
    ]
)

In [10]:
gamecities = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MGameCities.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WGameCities.csv')).assign(Gender='W')
    ]
)

In [11]:
seasons = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MSeasons.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WSeasons.csv')).assign(Gender='W')
    ]
)

In [12]:
conferencetourneygames = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MConferenceTourneyGames.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WConferenceTourneyGames.csv')).assign(Gender='W')
    ]
)

In [13]:

regularseasoncompactresults = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MRegularSeasonCompactResults.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WRegularSeasonCompactResults.csv')).assign(Gender='W')
    ]
)

In [14]:

regularseasondetailedresults = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MRegularSeasonDetailedResults.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WRegularSeasonDetailedResults.csv')).assign(Gender='W')
    ]
)

In [15]:
secondarytourneycompactresults = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MSecondaryTourneyCompactResults.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WSecondaryTourneyCompactResults.csv')).assign(Gender='W')
    ]
)

In [16]:
teams.to_csv(os.path.join(path,'data','processed','Teams.csv'),index=False)
teamconferences.to_csv(os.path.join(path,'data','processed','TeamConfereces.csv'),index=False)
ncaatourneyseeds.to_csv(os.path.join(path,'data','processed','NCAATourneySeeds.csv'),index=False)
secondarytourneyteams.to_csv(os.path.join(path,'data','processed','SecondaryTourneyTeams.csv'),index=False)
ncaatourneycompactresults.to_csv(os.path.join(path,'data','processed','NCAATourneyCompactResults.csv'),index=False)
ncaatourneydetailedresults.to_csv(os.path.join(path,'data','processed','NCAATourneyDetailedResults.csv'),index=False)
gamecities.to_csv(os.path.join(path,'data','processed','GameCities.csv'),index=False)
seasons.to_csv(os.path.join(path,'data','processed','Seasons.csv'),index=False)
conferencetourneygames.to_csv(os.path.join(path,'data','processed','ConferenceTourneyGames.csv'),index=False)
regularseasoncompactresults.to_csv(os.path.join(path,'data','processed','RegularSeasonCompactResults.csv'),index=False)
regularseasondetailedresults.to_csv(os.path.join(path,'data','processed','RegularSeasonDetailedResults.csv'),index=False)
secondarytourneycompactresults.to_csv(os.path.join(path,'data','processed','SecondaryTourneyCompactResults.csv'),index=False)

In [25]:
# Also append the remaining useful files to processed folder to use them for computation

coaches = pd.read_csv(os.path.join(path,'data','raw','MTeamCoaches.csv')).assign(Gender='M')
coaches.to_csv(os.path.join(path,'data','processed','Coaches.csv'))

masseyordinals = pd.read_csv(os.path.join(path,'data','raw','MMasseyOrdinals.csv')).assign(Gender='M')
masseyordinals.to_csv(os.path.join(path,'data','processed','MasseyOrdinals.csv'))

## Merging based on Keys

> Key = Season, Daynum, WTeamID, LTeamID, Gender

* NCAATournamentSessionDetailedResults
* GameCities
* Seasons
* ConferenceTourneyGames
---
* RegularSessionDetailedResults
* GameCities
* Seasons
* ConferenceTourneyGames
---
* SecondaryTourneyCompactResults
* GameCities
* Seasons
* ConferenceTourneyGames

In [18]:
ncaa = pd.read_csv(os.path.join(path,'data','processed','NCAATourneyDetailedResults.csv'))

regular = pd.read_csv(os.path.join(path,'data','processed','RegularSeasonDetailedResults.csv'))
# cities = pd.read_csv(os.path.join(path,'data','processed','GameCities.csv'))    Not required
# conferencetourneygames = pd.read_csv(os.path.join(path,'data','processed','ConferenceTourneyGames.csv'))

# secondary = pd.read_csv(os.path.join(path,'data','processed','RegularSeasonDetailedResults.csv'))

In [19]:
data = ncaa
data2 = regular

In [ ]:
# NCAA
# data = ncaa.merge(cities,on=['Season','DayNum','WTeamID','LTeamID','Gender'],how='left')
# data = data.merge(conferencetourneygames,on=['Season','DayNum','WTeamID','LTeamID','Gender'],how='left')

In [ ]:
# Regular
# data2 = regular.merge(cities,on=['Season','DayNum','WTeamID','LTeamID','Gender'],how='left')
# data2 = data2.merge(conferencetourneygames,on=['Season','DayNum','WTeamID','LTeamID','Gender'],how='left')

In [42]:
data

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF,Gender
0,2003,134,1421,92,1411,84,N,1,32,69,...,14,31,17,28,16,15,5,0,22,M
1,2003,136,1112,80,1436,51,N,0,31,66,...,7,7,8,26,12,17,10,3,15,M
2,2003,136,1113,84,1272,71,N,0,31,59,...,14,21,20,22,11,12,2,5,18,M
3,2003,136,1141,79,1166,73,N,0,29,53,...,12,17,14,17,20,21,6,6,21,M
4,2003,136,1143,76,1301,74,N,1,27,64,...,15,20,10,26,16,14,5,8,19,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2405,2025,147,3163,78,3425,64,N,0,27,60,...,23,26,13,29,7,15,8,2,18,W
2406,2025,147,3400,58,3395,47,N,0,24,61,...,19,21,11,27,8,21,1,3,14,W
2407,2025,151,3163,85,3417,51,N,0,33,60,...,7,8,8,21,11,19,5,2,12,W
2408,2025,151,3376,74,3400,57,N,0,29,57,...,9,12,9,20,10,14,6,5,17,W
2409,2025,153,3163,82,3376,59,N,0,30,62,...,13,18,17,19,9,11,6,4,17,W

In [43]:
data2

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF,Gender
0,2003,10,1104,68,1328,62,N,0,27,58,...,16,22,10,22,8,18,9,2,20,M
1,2003,10,1272,70,1393,63,N,0,26,62,...,9,20,20,25,7,12,8,6,16,M
2,2003,11,1266,73,1437,61,N,0,24,58,...,14,23,31,22,9,12,2,5,23,M
3,2003,11,1296,56,1457,50,N,0,18,38,...,8,15,17,20,9,19,4,3,23,M
4,2003,11,1400,77,1208,71,N,0,30,61,...,17,27,21,15,12,10,7,1,14,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210799,2026,118,3435,87,3397,77,A,0,35,66,...,9,10,9,20,9,7,2,13,14,W
210800,2026,118,3439,83,3438,82,A,0,27,65,...,18,25,9,22,15,4,3,14,19,W
210801,2026,118,3449,70,3332,69,A,0,27,59,...,13,16,9,20,13,6,2,14,16,W
210802,2026,118,3452,118,3153,60,H,0,42,72,...,14,24,6,19,9,2,1,17,25,W
210803,2026,118,3456,60,3423,41,A,0,22,61,...,7,10,3,19,8,6,5,20,17,W

In [20]:
data.columns

Index(['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore', 'WLoc',
       'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR',
       'WAst', 'WTO', 'WStl', 'WBlk', 'WPF', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3',
       'LFTM', 'LFTA', 'LOR', 'LDR', 'LAst', 'LTO', 'LStl', 'LBlk', 'LPF',
       'Gender'],
      dtype='object')

In [21]:
def ground(row):
    if row['WLoc'] == 'H':
        return 'A'
    elif row['WLoc'] == 'A':
        return 'H'
    else:
        return 'N'
    

data['LLoc'] = data.apply(ground,axis=1)
data2['LLoc'] = data2.apply(ground,axis=1)

In [22]:
# first I will have to separate winners and losers
dataw = data[['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore','WLoc',
       'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR',
       'WAst', 'WTO', 'WStl', 'WBlk', 'WPF','Gender']]

datal = data[['Season', 'DayNum','LTeamID', 'LScore', 'WTeamID', 'WScore','LLoc',
              'NumOT', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3','LFTM', 'LFTA', 'LOR', 'LDR',
              'LAst', 'LTO', 'LStl', 'LBlk', 'LPF','Gender']]

dataw.rename(columns={'WTeamID':'TeamID','LTeamID':'OppTeamID','LScore':'OppScore'},inplace=True)
datal.rename(columns={'LTeamID':'TeamID','WTeamID':'OppTeamID','WScore':'OppScore'},inplace=True)

In [23]:

data2w = data2[['Season', 'DayNum', 'WTeamID', 'WScore','LTeamID', 'LScore', 'WLoc',
       'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR',
       'WAst', 'WTO', 'WStl', 'WBlk', 'WPF','Gender']]

data2l = data2[['Season', 'DayNum','LTeamID', 'LScore', 'WTeamID', 'WScore','LLoc',
              'NumOT', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3','LFTM', 'LFTA', 'LOR', 'LDR',
              'LAst', 'LTO', 'LStl', 'LBlk', 'LPF','Gender']]

data2w.rename(columns={'WTeamID':'TeamID','LTeamID':'OppTeamID','LScore':'OppScore'},inplace=True)
data2l.rename(columns={'LTeamID':'TeamID','WTeamID':'OppTeamID','WScore':'OppScore'},inplace=True)

> Key = TeamID, Seasons, Gender
* NCAATourneySeeds   # No seeds for Secondary and Regular games
* MasseyOrdinals   # Only for Men
* TeamCoaches      # Only for Men
* TeamConferences

In [24]:
ncaatourneyseeds = pd.read_csv(os.path.join(path,'data','processed','NCAATourneySeeds.csv'))
# massey = pd.read_csv(os.path.join(path,'data','processed','MasseyOrdinals.csv'))
teamcoaches = pd.read_csv(os.path.join(path,'data','processed','Coaches.csv'))
teamconferences = pd.read_csv(os.path.join(path,'data','processed','TeamConfereces.csv'))

In [79]:
teams = pd.read_csv(os.path.join(path,'data','processed','Teams.csv'))

In [25]:
teamcoaches.columns

Index(['Unnamed: 0', 'Season', 'TeamID', 'FirstDayNum', 'LastDayNum',
       'CoachName', 'Gender'],
      dtype='object')

In [26]:
dataw = dataw.merge(ncaatourneyseeds,on=['Season','TeamID','Gender'],how='left')
# dataw = dataw.merge(massey,on=['Season','TeamID','Gender'],how='left')
dataw = dataw.merge(teamcoaches,on=['Season','TeamID','Gender'],how='left')
dataw = dataw.merge(teamconferences,on=['Season','TeamID','Gender'],how='left')

In [27]:
datal = datal.merge(ncaatourneyseeds,on=['Season','TeamID','Gender'],how='left')
# datal = datal.merge(massey,on=['Season','TeamID','Gender'],how='left')
datal = datal.merge(teamcoaches,on=['Season','TeamID','Gender'],how='left')
datal = datal.merge(teamconferences,on=['Season','TeamID','Gender'],how='left')

In [28]:
# data2w = data2w.merge(massey,on=['Season','TeamID','Gender'],how='left',indicator=True)
data2w = data2w.merge(teamcoaches,on=['Season','TeamID','Gender'],how='left')
data2w = data2w.merge(teamconferences,on=['Season','TeamID','Gender'],how='left')

In [29]:
# data2l = data2l.merge(massey,on=['Season','TeamID','Gender'],how='inner')
data2l = data2l.merge(teamcoaches,on=['Season','TeamID','Gender'],how='left')
data2l = data2l.merge(teamconferences,on=['Season','TeamID','Gender'],how='left')

In [30]:
data2l

,Season,DayNum,TeamID,LScore,OppTeamID,OppScore,LLoc,NumOT,LFGM,LFGA,...,LTO,LStl,LBlk,LPF,Gender,Unnamed: 0,FirstDayNum,LastDayNum,CoachName,ConfAbbrev
0,2003,10,1328,62,1104,68,N,0,22,53,...,18,9,2,20,M,5662.0,0.0,154.0,kelvin_sampson,big_twelve
1,2003,10,1393,63,1272,70,N,0,24,67,...,12,8,6,16,M,5722.0,0.0,154.0,jim_boeheim,big_east
2,2003,11,1437,61,1266,73,N,0,22,73,...,12,2,5,23,M,5764.0,0.0,154.0,jay_wright,big_east
3,2003,11,1457,50,1296,56,N,0,18,49,...,19,4,3,23,M,5782.0,0.0,154.0,gregg_marshall,big_south
4,2003,11,1208,71,1400,77,N,0,24,62,...,10,7,1,14,M,5558.0,0.0,154.0,jim_harrick,sec
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212437,2026,118,3397,77,3435,87,H,0,31,68,...,7,2,13,14,W,NaN,NaN,NaN,NaN,sec
212438,2026,118,3438,82,3439,83,H,0,30,60,...,4,3,14,19,W,NaN,NaN,NaN,NaN,acc
212439,2026,118,3332,69,3449,70,H,0,26,53,...,6,2,14,16,W,NaN,NaN,NaN,NaN,big_ten
212440,2026,118,3153,60,3452,118,A,0,22,53,...,2,1,17,25,W,NaN,NaN,NaN,NaN,big_twelve
212441,2026,118,3423,41,3456,60,H,0,14,48,...,6,5,20,17,W,NaN,NaN,NaN,NaN,caa

In [31]:
data2w

,Season,DayNum,TeamID,WScore,OppTeamID,OppScore,WLoc,NumOT,WFGM,WFGA,...,WTO,WStl,WBlk,WPF,Gender,Unnamed: 0,FirstDayNum,LastDayNum,CoachName,ConfAbbrev
0,2003,10,1104,68,1328,62,N,0,27,58,...,23,7,1,22,M,5462.0,0.0,154.0,mark_gottfried,sec
1,2003,10,1272,70,1393,63,N,0,26,62,...,13,4,4,18,M,5616.0,0.0,154.0,john_calipari,cusa
2,2003,11,1266,73,1437,61,N,0,24,58,...,10,5,2,25,M,5610.0,0.0,154.0,tom_crean,cusa
3,2003,11,1296,56,1457,50,N,0,18,38,...,12,14,2,18,M,5638.0,0.0,154.0,rob_judson,mac
4,2003,11,1400,77,1208,71,N,0,30,61,...,14,4,4,20,M,5730.0,0.0,154.0,rick_barnes,big_twelve
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211613,2026,118,3435,87,3397,77,A,0,35,66,...,5,3,14,14,W,NaN,NaN,NaN,NaN,sec
211614,2026,118,3439,83,3438,82,A,0,27,65,...,7,5,9,24,W,NaN,NaN,NaN,NaN,acc
211615,2026,118,3449,70,3332,69,A,0,27,59,...,7,2,11,17,W,NaN,NaN,NaN,NaN,big_ten
211616,2026,118,3452,118,3153,60,H,0,42,72,...,11,1,4,20,W,NaN,NaN,NaN,NaN,big_twelve
211617,2026,118,3456,60,3423,41,A,0,22,61,...,13,4,15,15,W,NaN,NaN,NaN,NaN,caa

In [32]:
print(dataw.columns)
print(datal.columns)
print(data2w.columns)
print(data2l.columns)

Index(['Season', 'DayNum', 'TeamID', 'WScore', 'OppTeamID', 'OppScore', 'WLoc',
       'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR',
       'WAst', 'WTO', 'WStl', 'WBlk', 'WPF', 'Gender', 'Seed', 'Unnamed: 0',
       'FirstDayNum', 'LastDayNum', 'CoachName', 'ConfAbbrev'],
      dtype='object')
Index(['Season', 'DayNum', 'TeamID', 'LScore', 'OppTeamID', 'OppScore', 'LLoc',
       'NumOT', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3', 'LFTM', 'LFTA', 'LOR', 'LDR',
       'LAst', 'LTO', 'LStl', 'LBlk', 'LPF', 'Gender', 'Seed', 'Unnamed: 0',
       'FirstDayNum', 'LastDayNum', 'CoachName', 'ConfAbbrev'],
      dtype='object')
Index(['Season', 'DayNum', 'TeamID', 'WScore', 'OppTeamID', 'OppScore', 'WLoc',
       'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR',
       'WAst', 'WTO', 'WStl', 'WBlk', 'WPF', 'Gender', 'Unnamed: 0',
       'FirstDayNum', 'LastDayNum', 'CoachName', 'ConfAbbrev'],
      dtype='object')
Index(['Season', 'DayNum', 'TeamID', 'LScore', 'OppTeamID', 'OppScore', 'LLoc',
       'NumOT', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3', 'LFTM', 'LFTA', 'LOR', 'LDR',
       'LAst', 'LTO', 'LStl', 'LBlk', 'LPF', 'Gender', 'Unnamed: 0',
       'FirstDayNum', 'LastDayNum', 'CoachName', 'ConfAbbrev'],
      dtype='object')

In [33]:
dataw.drop(columns='Unnamed: 0',inplace=True)
datal.drop(columns='Unnamed: 0',inplace=True)
data2w.drop(columns='Unnamed: 0',inplace=True)
data2l.drop(columns='Unnamed: 0',inplace=True)

In [34]:
dataw['Tournament'] = 'NCAA'
datal['Tournament'] = 'NCAA'
data2w['Tournament'] = 'Regular'
data2l['Tournament'] = 'Regular'

In [35]:
print(dataw.columns)
print(datal.columns)
print(data2w.columns)
print(data2l.columns)

Index(['Season', 'DayNum', 'TeamID', 'WScore', 'OppTeamID', 'OppScore', 'WLoc',
       'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR',
       'WAst', 'WTO', 'WStl', 'WBlk', 'WPF', 'Gender', 'Seed', 'FirstDayNum',
       'LastDayNum', 'CoachName', 'ConfAbbrev', 'Tournament'],
      dtype='object')
Index(['Season', 'DayNum', 'TeamID', 'LScore', 'OppTeamID', 'OppScore', 'LLoc',
       'NumOT', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3', 'LFTM', 'LFTA', 'LOR', 'LDR',
       'LAst', 'LTO', 'LStl', 'LBlk', 'LPF', 'Gender', 'Seed', 'FirstDayNum',
       'LastDayNum', 'CoachName', 'ConfAbbrev', 'Tournament'],
      dtype='object')
Index(['Season', 'DayNum', 'TeamID', 'WScore', 'OppTeamID', 'OppScore', 'WLoc',
       'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR',
       'WAst', 'WTO', 'WStl', 'WBlk', 'WPF', 'Gender', 'FirstDayNum',
       'LastDayNum', 'CoachName', 'ConfAbbrev', 'Tournament'],
      dtype='object')
Index(['Season', 'DayNum', 'TeamID', 'LScore', 'OppTeamID', 'OppScore', 'LLoc',
       'NumOT', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3', 'LFTM', 'LFTA', 'LOR', 'LDR',
       'LAst', 'LTO', 'LStl', 'LBlk', 'LPF', 'Gender', 'FirstDayNum',
       'LastDayNum', 'CoachName', 'ConfAbbrev', 'Tournament'],
      dtype='object')

In [36]:
dataw.rename(columns={
    'WScore':'Score',
    'WLoc':'Loc',
    'WFGM':'FGM',
    'WFGA':'FGA',
    'WFGA3':'FGA3',
    'WFGM3':'FGM3',
    'WFTM':'FTM',
    'WFTA':'FTA',
    'WOR':'OR',
    'WDR':'DR',
    'WAst':'Ast',
    'WTO':'TO',
    'WStl':'Stl',
    'WBlk':'Blk',
    'WPF':'PF',
    },inplace=True)

data2w.rename(columns={
    'WScore':'Score',
    'WLoc':'Loc',
    'WFGM':'FGM',
    'WFGA':'FGA',
    'WFGA3':'FGA3',
    'WFGM3':'FGM3',
    'WFTM':'FTM',
    'WFTA':'FTA',
    'WOR':'OR',
    'WDR':'DR',
    'WAst':'Ast',
    'WTO':'TO',
    'WStl':'Stl',
    'WBlk':'Blk',
    'WPF':'PF',
    },inplace=True)

In [37]:
datal.rename(columns={
    'LScore':'Score',
    'LLoc':'Loc',
    'LFGM':'FGM',
    'LFGA':'FGA',
    'LFGA3':'FGA3',
    'LFGM3':'FGM3',
    'LFTM':'FTM',
    'LFTA':'FTA',
    'LOR':'OR',
    'LDR':'DR',
    'LAst':'Ast',
    'LTO':'TO',
    'LStl':'Stl',
    'LBlk':'Blk',
    'LPF':'PF',
    },inplace=True)

data2l.rename(columns={
    'LScore':'Score',
    'LLoc':'Loc',
    'LFGM':'FGM',
    'LFGA':'FGA',
    'LFGA3':'FGA3',
    'LFGM3':'FGM3',
    'LFTM':'FTM',
    'LFTA':'FTA',
    'LOR':'OR',
    'LDR':'DR',
    'LAst':'Ast',
    'LTO':'TO',
    'LStl':'Stl',
    'LBlk':'Blk',
    'LPF':'PF',
    },inplace=True)

In [38]:
print(dataw.columns)
print(datal.columns)
print(data2w.columns)
print(data2l.columns)

Index(['Season', 'DayNum', 'TeamID', 'Score', 'OppTeamID', 'OppScore', 'Loc',
       'NumOT', 'FGM', 'FGA', 'FGM3', 'FGA3', 'FTM', 'FTA', 'OR', 'DR', 'Ast',
       'TO', 'Stl', 'Blk', 'PF', 'Gender', 'Seed', 'FirstDayNum', 'LastDayNum',
       'CoachName', 'ConfAbbrev', 'Tournament'],
      dtype='object')
Index(['Season', 'DayNum', 'TeamID', 'Score', 'OppTeamID', 'OppScore', 'Loc',
       'NumOT', 'FGM', 'FGA', 'FGM3', 'FGA3', 'FTM', 'FTA', 'OR', 'DR', 'Ast',
       'TO', 'Stl', 'Blk', 'PF', 'Gender', 'Seed', 'FirstDayNum', 'LastDayNum',
       'CoachName', 'ConfAbbrev', 'Tournament'],
      dtype='object')
Index(['Season', 'DayNum', 'TeamID', 'Score', 'OppTeamID', 'OppScore', 'Loc',
       'NumOT', 'FGM', 'FGA', 'FGM3', 'FGA3', 'FTM', 'FTA', 'OR', 'DR', 'Ast',
       'TO', 'Stl', 'Blk', 'PF', 'Gender', 'FirstDayNum', 'LastDayNum',
       'CoachName', 'ConfAbbrev', 'Tournament'],
      dtype='object')
Index(['Season', 'DayNum', 'TeamID', 'Score', 'OppTeamID', 'OppScore', 'Loc',
       'NumOT', 'FGM', 'FGA', 'FGM3', 'FGA3', 'FTM', 'FTA', 'OR', 'DR', 'Ast',
       'TO', 'Stl', 'Blk', 'PF', 'Gender', 'FirstDayNum', 'LastDayNum',
       'CoachName', 'ConfAbbrev', 'Tournament'],
      dtype='object')

In [39]:
final_df = pd.concat([dataw,datal,data2w,data2l],axis=0,ignore_index=True)

In [40]:
final_df.shape

(428892, 28)

In [41]:
final_df.sort_values(by=['Season','DayNum','TeamID'],inplace=True)

In [42]:
final_df.to_csv(os.path.join(path,'data','processed','FData.csv'),index=False)

In [163]:
final_df

,Season,DayNum,TeamID,Score,OppTeamID,OppScore,Loc,NumOT,FGM,FGA,...,Stl,Blk,PF,Gender,Seed,FirstDayNum,LastDayNum,CoachName,ConfAbbrev,Tournament
4832,2003,10,1104,68,1328,62,N,0,27,58,...,7,1,22,M,NaN,0.0,154.0,mark_gottfried,sec,Regular
216450,2003,10,1104,62,1328,68,N,0,22,53,...,9,2,20,M,NaN,0.0,154.0,mark_gottfried,sec,Regular
4833,2003,10,1272,70,1393,63,N,0,26,62,...,4,4,18,M,NaN,0.0,154.0,john_calipari,cusa,Regular
216451,2003,10,1272,63,1393,70,N,0,24,67,...,8,6,16,M,NaN,0.0,154.0,john_calipari,cusa,Regular
4834,2003,11,1266,73,1437,61,N,0,24,58,...,5,2,25,M,NaN,0.0,154.0,tom_crean,cusa,Regular
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
428065,2026,118,3449,69,3332,70,H,0,26,53,...,2,14,16,W,NaN,NaN,NaN,NaN,big_ten,Regular
216448,2026,118,3452,118,3153,60,H,0,42,72,...,1,4,20,W,NaN,NaN,NaN,NaN,big_twelve,Regular
428066,2026,118,3452,60,3153,118,A,0,22,53,...,1,17,25,W,NaN,NaN,NaN,NaN,big_twelve,Regular
216449,2026,118,3456,60,3423,41,A,0,22,61,...,4,15,15,W,NaN,NaN,NaN,NaN,caa,Regular
428067,2026,118,3456,41,3423,60,H,0,14,48,...,5,20,17,W,NaN,NaN,NaN,NaN,caa,Regular

# Feature Engineering

In [125]:
df = pd.read_csv(os.path.join(path,'data','processed','FData.csv'))

In [126]:
df.columns

Index(['Season', 'DayNum', 'TeamID', 'Score', 'OppTeamID', 'OppScore', 'Loc',
       'NumOT', 'FGM', 'FGA', 'FGM3', 'FGA3', 'FTM', 'FTA', 'OR', 'DR', 'Ast',
       'TO', 'Stl', 'Blk', 'PF', 'Gender', 'Seed', 'FirstDayNum', 'LastDayNum',
       'CoachName', 'ConfAbbrev', 'Tournament'],
      dtype='object')

In [127]:
df.isnull().sum() # No Null Values

Season              0
DayNum              0
TeamID              0
Score               0
OppTeamID           0
OppScore            0
Loc                 0
NumOT               0
FGM                 0
FGA                 0
FGM3                0
FGA3                0
FTM                 0
FTA                 0
OR                  0
DR                  0
Ast                 0
TO                  0
Stl                 0
Blk                 0
PF                  0
Gender              0
Seed           424060
FirstDayNum    175468
LastDayNum     175468
CoachName      175468
ConfAbbrev          0
Tournament          0
dtype: int64

In [128]:
df['FGA3'] = df['FGA3'] + 0.001
df['FTA'] = df['FTA'] + 0.001

In [129]:

df['FG%'] = df['FGM']/df['FGA']
df['FG%'].apply(lambda x: math.ceil(x * 10000) / 10000)

df['3P%'] = df['FGM3']/df['FGA3']
df['3P%'].apply(lambda x: math.ceil(x * 10000) / 10000)

df['FT%'] = df['FTM']/df['FTA']
df['FT%'].apply(lambda x: math.ceil(x * 10000) / 10000)

0         0.6111
1         0.5263
2         0.7273
3         0.4500
4         0.7059
           ...
428887    0.5833
428888    0.6334
428889    0.7143
428890    0.8749
428891    0.6666
Name: FT%, Length: 428892, dtype: float64

In [130]:
def possesion(row):
    calc = (row['FGA'] - row['OR'] + row['TO']) + (0.44*row['FTA'])
    return calc

In [131]:
df['Possessions'] = df.apply(lambda x: possesion(x),axis=1)

In [132]:
df.columns

Index(['Season', 'DayNum', 'TeamID', 'Score', 'OppTeamID', 'OppScore', 'Loc',
       'NumOT', 'FGM', 'FGA', 'FGM3', 'FGA3', 'FTM', 'FTA', 'OR', 'DR', 'Ast',
       'TO', 'Stl', 'Blk', 'PF', 'Gender', 'Seed', 'FirstDayNum', 'LastDayNum',
       'CoachName', 'ConfAbbrev', 'Tournament', 'FG%', '3P%', 'FT%',
       'Possessions'],
      dtype='object')

## Aggregation

In [133]:
df = df.sort_values(['Season', 'DayNum', 'TeamID'])

In [134]:
df['Win'] = (df['Score'] > df['OppScore']).astype(int)

In [135]:
df.to_csv(os.path.join(path,'data','final','Matchups.csv'),index=False)

In [136]:
grouped = df.groupby(['TeamID'])

In [137]:
agg_df = grouped.agg({
    'Score': 'mean',
    'FGM': 'mean',
    'FGA': 'mean',
    'FGM3': 'mean',
    'FGA3': 'mean',
    'FTM': 'mean',
    'FTA': 'mean',
    'OR': 'mean',
    'DR': 'mean',
    'Ast': 'mean',
    'TO': 'mean',
    'Stl': 'mean',
    'Blk': 'mean',
    'PF': 'mean',
    'FG%': 'mean',
    '3P%': 'mean',
    'FT%': 'mean',
    'Possessions': 'mean',
    'NumOT': 'mean'
}).reset_index()

In [138]:
agg_df['GamesPlayed'] = grouped.size().values

In [139]:
win_rate = grouped['Win'].mean().reset_index(name='WinRate')

In [140]:
agg_df = agg_df.merge(win_rate, on=['TeamID'])

In [141]:
df['RollingScore'] = df.groupby(['TeamID'])['Score']\
    .transform(lambda x: x.rolling(10, min_periods=1).mean())

In [142]:
recent = df.groupby(['TeamID'])['RollingScore'].last().reset_index()

In [143]:
home = df[df['Loc'] == 'H'].groupby(['TeamID'])['Score'].mean()
away = df[df['Loc'] == 'A'].groupby(['TeamID'])['Score'].mean()

In [144]:
final_team_df = agg_df.merge(recent, on=['TeamID'], how='left')

In [145]:
final_team_df

,TeamID,Score,FGM,FGA,FGM3,FGA3,FTM,FTA,OR,DR,...,Blk,PF,FG%,3P%,FT%,Possessions,NumOT,GamesPlayed,WinRate,RollingScore
0,1101,69.447293,24.230769,55.831909,6.435897,18.707553,14.549858,20.248863,8.564103,21.119658,...,2.663818,21.002849,0.435278,0.344498,0.713544,69.339699,0.074074,351,0.464387,70.1
1,1102,63.495376,22.043593,49.357992,7.527081,21.384091,11.881110,17.221608,6.710700,20.997358,...,2.542933,17.384412,0.449340,0.350729,0.687520,62.249898,0.038309,757,0.400264,66.4
2,1103,72.891421,25.324397,56.721180,8.230563,23.136389,14.012064,20.021107,10.477212,23.619303,...,3.427614,18.430295,0.448035,0.356537,0.697885,67.448697,0.072386,746,0.659517,83.9
3,1104,74.308642,25.829630,57.727160,7.419753,21.656556,15.229630,21.640506,11.490123,25.290123,...,4.591358,18.008642,0.448181,0.339584,0.702148,68.888489,0.070370,810,0.613580,92.3
4,1105,64.972561,22.527439,56.434451,5.519817,18.179354,14.397866,21.654963,11.074695,22.966463,...,3.567073,19.407012,0.400840,0.300706,0.662248,69.727879,0.060976,656,0.323171,72.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
734,3477,63.956140,23.070175,60.359649,5.859649,19.185211,11.956140,16.922053,8.552632,23.921053,...,4.017544,16.043860,0.384389,0.304590,0.718257,73.629914,0.035088,114,0.368421,60.9
735,3478,55.543478,19.402174,53.304348,5.717391,18.870565,11.021739,14.620565,8.532609,21.445652,...,3.391304,14.195652,0.365588,0.304472,0.746575,65.704788,0.054348,92,0.380435,57.3
736,3479,63.596154,21.634615,54.807692,8.153846,24.847154,12.173077,16.520231,6.230769,19.211538,...,2.288462,18.250000,0.396482,0.328815,0.740364,71.672748,0.076923,52,0.365385,72.4
737,3480,68.109091,23.818182,58.090909,6.945455,22.710091,13.527273,19.710091,9.690909,23.181818,...,4.454545,17.145455,0.411851,0.302956,0.687240,72.890622,0.145455,55,0.472727,70.9
738,3481,56.076923,20.730769,54.692308,5.000000,16.962538,9.615385,13.193308,11.115385,21.115385,...,5.307692,16.038462,0.381343,0.290975,0.739828,64.766594,0.076923,26,0.192308,59.3

In [146]:
final_team_df = teams.merge(final_team_df, on="TeamID", how="left")

In [147]:
final_team_df = final_team_df.fillna(0)

In [148]:
final_team_df.to_csv(os.path.join(path,'data','final','Dataset.csv'),index=False)

# Feature Scalings

In [149]:
df = pd.read_csv(os.path.join(path,'data','final','Dataset.csv'))

In [167]:
df

,Score,FGM,FGA,FGM3,FGA3,FTM,FTA,OR,DR,Ast,...,Blk,PF,FG%,3P%,FT%,Possessions,NumOT,GamesPlayed,WinRate,RollingScore
Key,,,,,,,,,,,,,,,,,,,,,
1101,0.924,0.701,0.878,0.436,0.648,0.596,0.664,0.491,0.673,0.580,...,0.282,0.672,0.079,0.065,0.117,0.924,0.016,1.274,0.465,0.926
1102,0.905,0.682,0.852,0.466,0.675,0.555,0.631,0.444,0.672,0.583,...,0.275,0.633,0.081,0.066,0.114,0.901,0.009,1.440,0.401,0.915
1103,0.935,0.711,0.881,0.483,0.692,0.589,0.662,0.530,0.696,0.587,...,0.324,0.645,0.081,0.067,0.115,0.918,0.016,1.437,0.660,0.965
1104,0.939,0.715,0.885,0.463,0.678,0.606,0.678,0.549,0.710,0.574,...,0.374,0.640,0.081,0.064,0.116,0.923,0.015,1.455,0.614,0.985
1105,0.910,0.686,0.880,0.408,0.642,0.594,0.678,0.541,0.690,0.548,...,0.330,0.655,0.074,0.058,0.111,0.925,0.013,1.409,0.324,0.935
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3477,0.907,0.691,0.894,0.419,0.653,0.557,0.627,0.491,0.699,0.564,...,0.351,0.616,0.071,0.058,0.118,0.937,0.008,1.031,0.369,0.896
3478,0.877,0.655,0.868,0.414,0.650,0.540,0.597,0.490,0.676,0.537,...,0.322,0.591,0.068,0.058,0.122,0.913,0.012,0.985,0.381,0.883
3479,0.906,0.678,0.874,0.481,0.707,0.560,0.622,0.430,0.653,0.552,...,0.259,0.643,0.073,0.062,0.121,0.931,0.017,0.863,0.366,0.933
3480,0.920,0.698,0.886,0.451,0.688,0.582,0.659,0.515,0.692,0.552,...,0.369,0.630,0.075,0.058,0.114,0.935,0.030,0.875,0.473,0.929
3481,0.879,0.669,0.873,0.390,0.628,0.513,0.577,0.542,0.673,0.563,...,0.400,0.616,0.071,0.056,0.121,0.910,0.017,0.716,0.193,0.891

In [151]:
# Set the key as Season+TeamID
'''
df['Key'] = df.apply(lambda x: str(int(x[0])) + '-' + str(int(x[1])),axis=1)
df.set_index('Key',inplace=True)
df.drop(columns=['Season','TeamID'],inplace=True)
'''
df.rename(columns={'TeamID':'Key'},inplace=True)
df.set_index('Key',inplace=True)

In [152]:
df

,TeamName,FirstD1Season,LastD1Season,Gender,Score,FGM,FGA,FGM3,FGA3,FTM,...,Blk,PF,FG%,3P%,FT%,Possessions,NumOT,GamesPlayed,WinRate,RollingScore
Key,,,,,,,,,,,,,,,,,,,,,
1101,Abilene Chr,2014.0,2026.0,M,69.447293,24.230769,55.831909,6.435897,18.707553,14.549858,...,2.663818,21.002849,0.435278,0.344498,0.713544,69.339699,0.074074,351.0,0.464387,70.1
1102,Air Force,1985.0,2026.0,M,63.495376,22.043593,49.357992,7.527081,21.384091,11.881110,...,2.542933,17.384412,0.449340,0.350729,0.687520,62.249898,0.038309,757.0,0.400264,66.4
1103,Akron,1985.0,2026.0,M,72.891421,25.324397,56.721180,8.230563,23.136389,14.012064,...,3.427614,18.430295,0.448035,0.356537,0.697885,67.448697,0.072386,746.0,0.659517,83.9
1104,Alabama,1985.0,2026.0,M,74.308642,25.829630,57.727160,7.419753,21.656556,15.229630,...,4.591358,18.008642,0.448181,0.339584,0.702148,68.888489,0.070370,810.0,0.613580,92.3
1105,Alabama A&M,2000.0,2026.0,M,64.972561,22.527439,56.434451,5.519817,18.179354,14.397866,...,3.567073,19.407012,0.400840,0.300706,0.662248,69.727879,0.060976,656.0,0.323171,72.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3477,East Texas A&M,0.0,0.0,W,63.956140,23.070175,60.359649,5.859649,19.185211,11.956140,...,4.017544,16.043860,0.384389,0.304590,0.718257,73.629914,0.035088,114.0,0.368421,60.9
3478,Le Moyne,0.0,0.0,W,55.543478,19.402174,53.304348,5.717391,18.870565,11.021739,...,3.391304,14.195652,0.365588,0.304472,0.746575,65.704788,0.054348,92.0,0.380435,57.3
3479,Mercyhurst,0.0,0.0,W,63.596154,21.634615,54.807692,8.153846,24.847154,12.173077,...,2.288462,18.250000,0.396482,0.328815,0.740364,71.672748,0.076923,52.0,0.365385,72.4
3480,West Georgia,0.0,0.0,W,68.109091,23.818182,58.090909,6.945455,22.710091,13.527273,...,4.454545,17.145455,0.411851,0.302956,0.687240,72.890622,0.145455,55.0,0.472727,70.9
3481,New Haven,0.0,0.0,W,56.076923,20.730769,54.692308,5.000000,16.962538,9.615385,...,5.307692,16.038462,0.381343,0.290975,0.739828,64.766594,0.076923,26.0,0.192308,59.3

In [153]:
df.describe()

,FirstD1Season,LastD1Season,Score,FGM,FGA,FGM3,FGA3,FTM,FTA,OR,...,Blk,PF,FG%,3P%,FT%,Possessions,NumOT,GamesPlayed,WinRate,RollingScore
count,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,...,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000
mean,997.475000,1015.121053,65.253364,23.278428,55.769225,6.081202,18.542835,12.615305,18.030257,10.526899,...,3.291307,17.169601,0.407391,0.316458,0.677990,67.272617,0.058256,564.331579,0.475150,67.682632
std,995.533409,1013.128409,12.064675,4.276486,9.684879,1.464656,3.956584,2.535217,3.610032,2.275098,...,0.813231,3.145317,0.073832,0.058045,0.116435,11.575251,0.019408,185.958353,0.146733,13.891958
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,63.212540,22.729395,55.714690,5.443458,17.432090,11.844156,17.001956,9.857542,...,2.930097,16.850546,0.395728,0.306313,0.682549,67.387436,0.047276,489.000000,0.391653,63.275000
50%,1985.000000,1985.500000,67.513726,23.970993,57.125037,6.321885,18.982481,12.949409,18.552365,10.766660,...,3.305918,17.660139,0.421127,0.327772,0.697572,68.980877,0.058824,530.000000,0.477039,69.950000
75%,1985.000000,2026.000000,70.500407,24.964687,58.520372,6.945826,20.453166,14.004560,20.023034,11.659758,...,3.694280,18.419949,0.440096,0.342836,0.711112,70.711030,0.070158,717.250000,0.568497,75.300000
max,2026.000000,2026.000000,82.009585,31.428115,69.898785,10.124294,29.767478,16.429448,23.059108,16.346154,...,6.369458,21.373494,0.505980,0.380310,0.767498,79.900197,0.145455,852.000000,0.931310,92.300000

In [154]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 760 entries, 1101 to 3481
Data columns (total 26 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   TeamName       760 non-null    object
 1   FirstD1Season  760 non-null    float64
 2   LastD1Season   760 non-null    float64
 3   Gender         760 non-null    object
 4   Score          760 non-null    float64
 5   FGM            760 non-null    float64
 6   FGA            760 non-null    float64
 7   FGM3           760 non-null    float64
 8   FGA3           760 non-null    float64
 9   FTM            760 non-null    float64
 10  FTA            760 non-null    float64
 11  OR             760 non-null    float64
 12  DR             760 non-null    float64
 13  Ast            760 non-null    float64
 14  TO             760 non-null    float64
 15  Stl            760 non-null    float64
 16  Blk            760 non-null    float64
 17  PF             760 non-null    float64
 18  FG%            760 non-null    float64
 19  3P%            760 non-null    float64
 20  FT%            760 non-null    float64
 21  Possessions    760 non-null    float64
 22  NumOT          760 non-null    float64
 23  GamesPlayed    760 non-null    float64
 24  WinRate        760 non-null    float64
 25  RollingScore   760 non-null    float64
dtypes: float64(24), object(2)
memory usage: 160.3+ KB

In [155]:
df = df[['Score', 'FGM',
       'FGA', 'FGM3', 'FGA3', 'FTM', 'FTA', 'OR', 'DR', 'Ast', 'TO', 'Stl',
       'Blk', 'PF', 'FG%', '3P%', 'FT%', 'Possessions', 'NumOT', 'GamesPlayed',
       'WinRate', 'RollingScore']]

In [156]:
# So as to make everything independent of data distribution, I will log transformations

for i in df.columns:
    if i!= 'WinRate':
        df[i] = df[i].apply(lambda x: (np.log(1+x)/np.log(100)))
    df[i] = df[i].apply(lambda x: math.ceil(1000*x)/1000)

In [157]:
df

,Score,FGM,FGA,FGM3,FGA3,FTM,FTA,OR,DR,Ast,...,Blk,PF,FG%,3P%,FT%,Possessions,NumOT,GamesPlayed,WinRate,RollingScore
Key,,,,,,,,,,,,,,,,,,,,,
1101,0.924,0.701,0.878,0.436,0.648,0.596,0.664,0.491,0.673,0.580,...,0.282,0.672,0.079,0.065,0.117,0.924,0.016,1.274,0.465,0.926
1102,0.905,0.682,0.852,0.466,0.675,0.555,0.631,0.444,0.672,0.583,...,0.275,0.633,0.081,0.066,0.114,0.901,0.009,1.440,0.401,0.915
1103,0.935,0.711,0.881,0.483,0.692,0.589,0.662,0.530,0.696,0.587,...,0.324,0.645,0.081,0.067,0.115,0.918,0.016,1.437,0.660,0.965
1104,0.939,0.715,0.885,0.463,0.678,0.606,0.678,0.549,0.710,0.574,...,0.374,0.640,0.081,0.064,0.116,0.923,0.015,1.455,0.614,0.985
1105,0.910,0.686,0.880,0.408,0.642,0.594,0.678,0.541,0.690,0.548,...,0.330,0.655,0.074,0.058,0.111,0.925,0.013,1.409,0.324,0.935
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3477,0.907,0.691,0.894,0.419,0.653,0.557,0.627,0.491,0.699,0.564,...,0.351,0.616,0.071,0.058,0.118,0.937,0.008,1.031,0.369,0.896
3478,0.877,0.655,0.868,0.414,0.650,0.540,0.597,0.490,0.676,0.537,...,0.322,0.591,0.068,0.058,0.122,0.913,0.012,0.985,0.381,0.883
3479,0.906,0.678,0.874,0.481,0.707,0.560,0.622,0.430,0.653,0.552,...,0.259,0.643,0.073,0.062,0.121,0.931,0.017,0.863,0.366,0.933
3480,0.920,0.698,0.886,0.451,0.688,0.582,0.659,0.515,0.692,0.552,...,0.369,0.630,0.075,0.058,0.114,0.935,0.030,0.875,0.473,0.929
3481,0.879,0.669,0.873,0.390,0.628,0.513,0.577,0.542,0.673,0.563,...,0.400,0.616,0.071,0.056,0.121,0.910,0.017,0.716,0.193,0.891

In [158]:
df.to_csv(os.path.join(path,'data','final','Dataset.csv'))

In [159]:
matchups = pd.read_csv(os.path.join(path,'data','final','Matchups.csv'))

In [161]:
target = matchups[['Season','TeamID','OppTeamID','Win']]

In [162]:
target['Win'].value_counts()

Win
0    214858
1    214034
Name: count, dtype: int64

In [163]:
matchups

,Season,DayNum,TeamID,Score,OppTeamID,OppScore,Loc,NumOT,FGM,FGA,...,FirstDayNum,LastDayNum,CoachName,ConfAbbrev,Tournament,FG%,3P%,FT%,Possessions,Win
0,2003,10,1104,68,1328,62,N,0,27,58,...,0.0,154.0,mark_gottfried,sec,Regular,0.465517,0.214270,0.611077,74.92044,1
1,2003,10,1272,70,1393,63,N,0,26,62,...,0.0,154.0,john_calipari,cusa,Regular,0.419355,0.399980,0.526288,68.36044,1
2,2003,10,1328,62,1104,68,N,0,22,53,...,0.0,154.0,kelvin_sampson,big_twelve,Regular,0.415094,0.199980,0.727240,70.68044,0
3,2003,10,1393,63,1272,70,N,0,24,67,...,0.0,154.0,jim_boeheim,big_east,Regular,0.358209,0.249990,0.449978,67.80044,0
4,2003,11,1186,55,1458,81,A,0,20,46,...,0.0,154.0,ray_giacoletti,big_sky,Regular,0.434783,0.272702,0.705841,66.48044,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
428887,2026,118,3449,70,3332,69,A,0,27,59,...,NaN,NaN,NaN,big_ten,Regular,0.457627,0.333321,0.583285,61.28044,1
428888,2026,118,3452,118,3153,60,H,0,42,72,...,NaN,NaN,NaN,big_twelve,Regular,0.583333,0.499983,0.633312,82.20044,1
428889,2026,118,3456,60,3423,41,A,0,22,61,...,NaN,NaN,NaN,caa,Regular,0.360656,0.333315,0.714235,64.16044,1
428890,2026,118,3458,52,3234,81,H,0,19,63,...,NaN,NaN,NaN,big_ten,Regular,0.301587,0.241371,0.874891,61.52044,0
428891,2026,118,3462,71,3166,73,H,0,29,59,...,NaN,NaN,NaN,big_east,Regular,0.491525,0.437473,0.666593,57.96044,0

In [166]:
matchups.nunique()

Season           24
DayNum          153
TeamID          739
Score           128
OppTeamID       739
OppScore        128
Loc               3
NumOT             7
FGM              55
FGA              86
FGM3             28
FGA3             64
FTM              51
FTA              67
OR               40
DR               53
Ast              45
TO               50
Stl              35
Blk              36
PF               46
Gender            2
Seed             96
FirstDayNum      55
LastDayNum       56
CoachName      1108
ConfAbbrev       36
Tournament        2
FG%            1340
3P%             760
FT%             927
Possessions    1568
Win               2
dtype: int64

In [172]:
matchups['Key'] = matchups.apply(lambda x: str(x[2]) + '-' + str(x[4]),axis=1)

In [173]:
matchups.to_csv(os.path.join(path,'data','final','Matchups.csv'))

In [121]:
matchups.groupby(by=['Key']).Win.mean()

Key
1101-1102    1.0
1101-1112    0.0
1101-1115    1.0
1101-1116    0.0
1101-1117    0.5
            ...
3481-3462    0.0
3481-3463    0.0
3481-3476    0.5
3481-3478    0.0
3481-3479    0.0
Name: Win, Length: 83094, dtype: float64

In [171]:
pd.Series(teams['TeamID'].apply(lambda x: str(x))).to_csv(os.path.join(path,'data','processed','Team_IDs.csv'),index=False)

In [122]:
teams

     TeamID        TeamName  FirstD1Season  LastD1Season Gender
0      1101     Abilene Chr         2014.0        2026.0      M
1      1102       Air Force         1985.0        2026.0      M
2      1103           Akron         1985.0        2026.0      M
3      1104         Alabama         1985.0        2026.0      M
4      1105     Alabama A&M         2000.0        2026.0      M
..      ...             ...            ...           ...    ...
755    3477  East Texas A&M            NaN           NaN      W
756    3478        Le Moyne            NaN           NaN      W
757    3479      Mercyhurst            NaN           NaN      W
758    3480    West Georgia            NaN           NaN      W
759    3481       New Haven            NaN           NaN      W

[760 rows x 5 columns]