In [1]:
import pandas as pd
import numpy as np
import os

import warnings
warnings.filterwarnings('ignore')

from dotenv import load_dotenv
load_dotenv()

True

In [2]:
dir = os.getenv('DIR')
os.getcwd()
os.chdir(dir)
path = os.getcwd()

In [3]:
# Downloading the data directly from the Kaggle Servers
# kagglehub.competition_download('march-machine-learning-mania-2026')

# Merging CSV Files

In [5]:
os.listdir(os.path.join(path,'data','raw'))

['Cities.csv',
 'Conferences.csv',
 'MConferenceTourneyGames.csv',
 'MGameCities.csv',
 'MMasseyOrdinals.csv',
 'MNCAATourneyCompactResults.csv',
 'MNCAATourneyDetailedResults.csv',
 'MNCAATourneySeedRoundSlots.csv',
 'MNCAATourneySeeds.csv',
 'MNCAATourneySlots.csv',
 'MRegularSeasonCompactResults.csv',
 'MRegularSeasonDetailedResults.csv',
 'MSeasons.csv',
 'MSecondaryTourneyCompactResults.csv',
 'MSecondaryTourneyTeams.csv',
 'MTeamCoaches.csv',
 'MTeamConferences.csv',
 'MTeams.csv',
 'MTeamSpellings.csv',
 'SampleSubmissionStage1.csv',
 'SampleSubmissionStage2.csv',
 'WConferenceTourneyGames.csv',
 'WGameCities.csv',
 'WNCAATourneyCompactResults.csv',
 'WNCAATourneyDetailedResults.csv',
 'WNCAATourneySeeds.csv',
 'WNCAATourneySlots.csv',
 'WRegularSeasonCompactResults.csv',
 'WRegularSeasonDetailedResults.csv',
 'WSeasons.csv',
 'WSecondaryTourneyCompactResults.csv',
 'WSecondaryTourneyTeams.csv',
 'WTeamConferences.csv',
 'WTeams.csv',
 'WTeamSpellings.csv']

## Merging Men and Women Files

In [3]:
# Teams

teams = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MTeams.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WTeams.csv')).assign(Gender='W')
    ]
)

In [4]:

teamconferences = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MTeamConferences.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WTeamConferences.csv')).assign(Gender='W')
    ]
)

In [5]:

ncaatourneyseeds = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MNCAATourneySeeds.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WNCAATourneySeeds.csv')).assign(Gender='W')
    ]
)

In [6]:

secondarytourneyteams = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MSecondaryTourneyTeams.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WSecondaryTourneyTeams.csv')).assign(Gender='W')
    ]
)

In [7]:

secondarytourneycompactresults = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MSecondaryTourneyCompactResults.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WSecondaryTourneyCompactResults.csv')).assign(Gender='W')
    ]
)

In [8]:

ncaatourneycompactresults = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MNCAATourneyCompactResults.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WNCAATourneyCompactResults.csv')).assign(Gender='W')
    ]
)

In [9]:
ncaatourneydetailedresults = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MNCAATourneyDetailedResults.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WNCAATourneyDetailedResults.csv')).assign(Gender='W')
    ]
)

In [10]:
gamecities = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MGameCities.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WGameCities.csv')).assign(Gender='W')
    ]
)

In [11]:
seasons = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MSeasons.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WSeasons.csv')).assign(Gender='W')
    ]
)

In [12]:
conferencetourneygames = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MConferenceTourneyGames.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WConferenceTourneyGames.csv')).assign(Gender='W')
    ]
)

In [13]:

regularseasoncompactresults = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MRegularSeasonCompactResults.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WRegularSeasonCompactResults.csv')).assign(Gender='W')
    ]
)

In [14]:

regularseasondetailedresults = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MRegularSeasonDetailedResults.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WRegularSeasonDetailedResults.csv')).assign(Gender='W')
    ]
)

In [15]:
secondarytourneycompactresults = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MSecondaryTourneyCompactResults.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WSecondaryTourneyCompactResults.csv')).assign(Gender='W')
    ]
)

In [24]:
teams.to_csv(os.path.join(path,'data','processed','Teams.csv'))
teamconferences.to_csv(os.path.join(path,'data','processed','TeamConfereces.csv'))
ncaatourneyseeds.to_csv(os.path.join(path,'data','processed','NCAATourneySeeds.csv'))
secondarytourneyteams.to_csv(os.path.join(path,'data','processed','SecondaryTourneyTeams.csv'))
ncaatourneycompactresults.to_csv(os.path.join(path,'data','processed','NCAATourneyCompactResults.csv'))
ncaatourneydetailedresults.to_csv(os.path.join(path,'data','processed','NCAATourneyDetailedResults.csv'))
gamecities.to_csv(os.path.join(path,'data','processed','GameCities.csv'))
seasons.to_csv(os.path.join(path,'data','processed','Seasons.csv'))
conferencetourneygames.to_csv(os.path.join(path,'data','processed','ConferenceTourneyGames.csv'))
regularseasoncompactresults.to_csv(os.path.join(path,'data','processed','RegularSeasonCompactResults.csv'))
regularseasondetailedresults.to_csv(os.path.join(path,'data','processed','RegularSeasonDetailedResults.csv'))
secondarytourneycompactresults.to_csv(os.path.join(path,'data','processed','SecondaryTourneyCompactResults.csv'))

In [25]:
# Also append the remaining useful files to processed folder to use them for computation

coaches = pd.read_csv(os.path.join(path,'data','raw','MTeamCoaches.csv')).assign(Gender='M')
coaches.to_csv(os.path.join(path,'data','processed','Coaches.csv'))

masseyordinals = pd.read_csv(os.path.join(path,'data','raw','MMasseyOrdinals.csv')).assign(Gender='M')
masseyordinals.to_csv(os.path.join(path,'data','processed','MasseyOrdinals.csv'))

## Merging based on Keys

> Key = Season, Daynum, WTeamID, LTeamID, Gender

* NCAATournamentSessionDetailedResults
* GameCities
* Seasons
* ConferenceTourneyGames
---
* RegularSessionDetailedResults
* GameCities
* Seasons
* ConferenceTourneyGames
---
* SecondaryTourneyCompactResults
* GameCities
* Seasons
* ConferenceTourneyGames

In [ ]:
ncaa = pd.read_csv(os.path.join(path,'data','processed','NCAATourneyDetailedResults.csv'))
ncaa.drop(columns='Unnamed: 0',inplace=True)

regular = pd.read_csv(os.path.join(path,'data','processed','RegularSeasonDetailedResults.csv'))
regular.drop(columns='Unnamed: 0',inplace=True)

# secondary = pd.read_csv(os.path.join(path,'data','processed','RegularSeasonDetailedResults.csv'))

cities = pd.read_csv(os.path.join(path,'data','processed','GameCities.csv'))
cities.drop(columns='Unnamed: 0',inplace=True)



conferencetourneygames = pd.read_csv(os.path.join(path,'data','processed','ConferenceTourneyGames.csv'))
conferencetourneygames.drop(columns='Unnamed: 0',inplace=True)

In [ ]:
# NCAA
data = ncaa.merge(cities,on=['Season','DayNum','WTeamID','LTeamID','Gender'],how='left')
data = data.merge(conferencetourneygames,on=['Season','DayNum','WTeamID','LTeamID','Gender'],how='left')

In [68]:
# Regular
data2 = regular.merge(cities,on=['Season','DayNum','WTeamID','LTeamID','Gender'],how='left')
data2 = data2.merge(conferencetourneygames,on=['Season','DayNum','WTeamID','LTeamID','Gender'],how='left')

In [67]:
data

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LDR,LAst,LTO,LStl,LBlk,LPF,Gender,CRType,CityID,ConfAbbrev
0,2003,134,1421,92,1411,84,N,1,32,69,...,28,16,15,5,0,22,M,NaN,NaN,NaN
1,2003,136,1112,80,1436,51,N,0,31,66,...,26,12,17,10,3,15,M,NaN,NaN,NaN
2,2003,136,1113,84,1272,71,N,0,31,59,...,22,11,12,2,5,18,M,NaN,NaN,NaN
3,2003,136,1141,79,1166,73,N,0,29,53,...,17,20,21,6,6,21,M,NaN,NaN,NaN
4,2003,136,1143,76,1301,74,N,1,27,64,...,26,16,14,5,8,19,M,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2405,2025,147,3163,78,3425,64,N,0,27,60,...,29,7,15,8,2,18,W,NCAA,4324.0,NaN
2406,2025,147,3400,58,3395,47,N,0,24,61,...,27,8,21,1,3,14,W,NCAA,4030.0,NaN
2407,2025,151,3163,85,3417,51,N,0,33,60,...,21,11,19,5,2,12,W,NCAA,4342.0,NaN
2408,2025,151,3376,74,3400,57,N,0,29,57,...,20,10,14,6,5,17,W,NCAA,4342.0,NaN
2409,2025,153,3163,82,3376,59,N,0,30,62,...,19,9,11,6,4,17,W,NCAA,4342.0,NaN

In [69]:
data2

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LDR,LAst,LTO,LStl,LBlk,LPF,Gender,CRType,CityID,ConfAbbrev
0,2003,10,1104,68,1328,62,N,0,27,58,...,22,8,18,9,2,20,M,NaN,NaN,NaN
1,2003,10,1272,70,1393,63,N,0,26,62,...,25,7,12,8,6,16,M,NaN,NaN,NaN
2,2003,11,1266,73,1437,61,N,0,24,58,...,22,9,12,2,5,23,M,NaN,NaN,NaN
3,2003,11,1296,56,1457,50,N,0,18,38,...,20,9,19,4,3,23,M,NaN,NaN,NaN
4,2003,11,1400,77,1208,71,N,0,30,61,...,15,12,10,7,1,14,M,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210799,2026,118,3435,87,3397,77,A,0,35,66,...,20,9,7,2,13,14,W,Regular,4180.0,NaN
210800,2026,118,3439,83,3438,82,A,0,27,65,...,22,15,4,3,14,19,W,Regular,4067.0,NaN
210801,2026,118,3449,70,3332,69,A,0,27,59,...,20,13,6,2,14,16,W,Regular,4112.0,NaN
210802,2026,118,3452,118,3153,60,H,0,42,72,...,19,9,2,1,17,25,W,Regular,4224.0,NaN
210803,2026,118,3456,60,3423,41,A,0,22,61,...,19,8,6,5,20,17,W,Regular,4370.0,NaN

In [73]:
data.columns

Index(['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore', 'WLoc',
       'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR',
       'WAst', 'WTO', 'WStl', 'WBlk', 'WPF', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3',
       'LFTM', 'LFTA', 'LOR', 'LDR', 'LAst', 'LTO', 'LStl', 'LBlk', 'LPF',
       'Gender', 'CRType', 'CityID', 'ConfAbbrev'],
      dtype='object')

In [ ]:
# first I will have to separate winners and losers
dataw = data[['Season', 'DayNum', 'WTeamID', 'WScore', 'WLoc',
       'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR',
       'WAst', 'WTO', 'WStl', 'WBlk', 'WPF','Gender', 'CRType', 'CityID', 'ConfAbbrev']]

datal = data[['Season', 'DayNum','LTeamID', 'LScore',
              'NumOT', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3','LFTM', 'LFTA', 'LOR', 'LDR',
              'LAst', 'LTO', 'LStl', 'LBlk', 'LPF','Gender', 'CRType', 'CityID', 'ConfAbbrev']]

dataw.rename(columns={'WTeamID':'TeamID'},inplace=True)
datal.rename(columns={'LTeamID':'TeamID'},inplace=True)

C:\Users\Sanket\AppData\Local\Temp\ipykernel_36392\3410070390.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datal.rename(columns={'LTeamID':'TeamID'},inplace=True)

In [ ]:

data2w = data2[['Season', 'DayNum', 'WTeamID', 'WScore', 'WLoc',
       'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR',
       'WAst', 'WTO', 'WStl', 'WBlk', 'WPF','Gender', 'CRType', 'CityID', 'ConfAbbrev']]

data2l = data2[['Season', 'DayNum','LTeamID', 'LScore',
              'NumOT', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3','LFTM', 'LFTA', 'LOR', 'LDR',
              'LAst', 'LTO', 'LStl', 'LBlk', 'LPF','Gender', 'CRType', 'CityID', 'ConfAbbrev']]

data2w.rename(columns={'WTeamID':'TeamID'},inplace=True)
data2l.rename(columns={'LTeamID':'TeamID'},inplace=True)

C:\Users\Sanket\AppData\Local\Temp\ipykernel_36392\2922518759.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2l.rename(columns={'LTeamID':'TeamID'},inplace=True)

> Key = TeamID, Seasons, Gender
* NCAATourneySeeds   # No seeds for Secondary and Regular games
* MasseyOrdinals   # Only for Men
* TeamCoaches      # Only for Men
* TeamConferences

In [72]:
ncaatourneyseeds = pd.read_csv(os.path.join(path,'data','processed','NCAATourneySeeds.csv'))
massey = pd.read_csv(os.path.join(path,'data','processed','MasseyOrdinals.csv'))
teamcoaches = pd.read_csv(os.path.join(path,'data','processed','Coaches.csv'))
teamconferences = pd.read_csv(os.path.join(path,'data','processed','TeamConfereces.csv'))

In [81]:
teamconferences.drop(columns='Unnamed: 0',inplace=True)

In [ ]:
dataw = dataw.merge(ncaatourneyseeds,on=['Season','TeamID','Gender'],how='left')
dataw = dataw.merge(massey,on=['Season','TeamID','Gender'],how='left')
dataw = dataw.merge(teamcoaches,on=['Season','TeamID','Gender'],how='left')
dataw = dataw.merge(teamconferences,on=['Season','TeamID','Gender'],how='left')

In [87]:
datal = datal.merge(ncaatourneyseeds,on=['Season','TeamID','Gender'],how='left')
datal = datal.merge(massey,on=['Season','TeamID','Gender'],how='left')
datal = datal.merge(teamcoaches,on=['Season','TeamID','Gender'],how='left')
datal = datal.merge(teamconferences,on=['Season','TeamID','Gender'],how='left')

In [90]:
# data2w = data2w.merge(massey,on=['Season','TeamID','Gender'],how='left',indicator=True)
data2w = data2w.merge(teamcoaches,on=['Season','TeamID','Gender'],how='left')
data2w = data2w.merge(teamconferences,on=['Season','TeamID','Gender'],how='left')

In [ ]:
# data2l = data2l.merge(massey,on=['Season','TeamID','Gender'],how='inner')
data2l = data2l.merge(teamcoaches,on=['Season','TeamID','Gender'],how='left')
data2l = data2l.merge(teamconferences,on=['Season','TeamID','Gender'],how='left')

MemoryError: Unable to allocate 2.62 GiB for an array with shape (4, 87925840) and data type float64

In [ ]:
chunks = []
for chunk in pd.read_csv(os.path.join(path,'data','processed','MasseyOrdinals.csv'), chunksize=3000):
    merged = pd.merge(chunk, data2l, on=['TeamID','Season','Gender'], how='inner')
    chunks.append(merged)
data2l = pd.concat(chunks, ignore_index=True)

:

In [ ]:
chunks = []
for chunk in pd.read_csv(os.path.join(path,'data','processed','MasseyOrdinals.csv'), chunksize=500000):
    merged = pd.merge(chunk, data2w, on=['TeamID','Season','Gender'], how='inner')
    chunks.append(merged)
data2w = pd.concat(chunks, ignore_index=True)

In [97]:
data2w

,Season,DayNum,TeamID,WScore,WLoc,NumOT,WFGM,WFGA,WFGM3,WFGA3,...,WPF,Gender,CRType,CityID,ConfAbbrev_x,Unnamed: 0,FirstDayNum,LastDayNum,CoachName,ConfAbbrev_y
0,2003,10,1104,68,N,0,27,58,3,14,...,22,M,NaN,NaN,NaN,5462.0,0.0,154.0,mark_gottfried,sec
1,2003,10,1272,70,N,0,26,62,8,20,...,18,M,NaN,NaN,NaN,5616.0,0.0,154.0,john_calipari,cusa
2,2003,11,1266,73,N,0,24,58,8,18,...,25,M,NaN,NaN,NaN,5610.0,0.0,154.0,tom_crean,cusa
3,2003,11,1296,56,N,0,18,38,3,9,...,18,M,NaN,NaN,NaN,5638.0,0.0,154.0,rob_judson,mac
4,2003,11,1400,77,N,0,30,61,6,14,...,20,M,NaN,NaN,NaN,5730.0,0.0,154.0,rick_barnes,big_twelve
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211613,2026,118,3435,87,A,0,35,66,11,22,...,14,W,Regular,4180.0,NaN,NaN,NaN,NaN,NaN,sec
211614,2026,118,3439,83,A,0,27,65,10,26,...,24,W,Regular,4067.0,NaN,NaN,NaN,NaN,NaN,acc
211615,2026,118,3449,70,A,0,27,59,9,27,...,17,W,Regular,4112.0,NaN,NaN,NaN,NaN,NaN,big_ten
211616,2026,118,3452,118,H,0,42,72,15,30,...,20,W,Regular,4224.0,NaN,NaN,NaN,NaN,NaN,big_twelve
211617,2026,118,3456,60,A,0,22,61,6,18,...,15,W,Regular,4370.0,NaN,NaN,NaN,NaN,NaN,caa

# Feature Engineering

In [45]:
ncaad

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF,Gender
0,2003,134,1421,92,1411,84,N,1,32,69,...,14,31,17,28,16,15,5,0,22,M
1,2003,136,1112,80,1436,51,N,0,31,66,...,7,7,8,26,12,17,10,3,15,M
2,2003,136,1113,84,1272,71,N,0,31,59,...,14,21,20,22,11,12,2,5,18,M
3,2003,136,1141,79,1166,73,N,0,29,53,...,12,17,14,17,20,21,6,6,21,M
4,2003,136,1143,76,1301,74,N,1,27,64,...,15,20,10,26,16,14,5,8,19,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2405,2025,147,3163,78,3425,64,N,0,27,60,...,23,26,13,29,7,15,8,2,18,W
2406,2025,147,3400,58,3395,47,N,0,24,61,...,19,21,11,27,8,21,1,3,14,W
2407,2025,151,3163,85,3417,51,N,0,33,60,...,7,8,8,21,11,19,5,2,12,W
2408,2025,151,3376,74,3400,57,N,0,29,57,...,9,12,9,20,10,14,6,5,17,W
2409,2025,153,3163,82,3376,59,N,0,30,62,...,13,18,17,19,9,11,6,4,17,W

In [49]:
ncaa = pd.read_csv(os.path.join(path,'data','processed','NCAATourneyDetailedResults.csv'))
regular = pd.read_csv(os.path.join(path,'data','processed','RegularSeasonDetailedResults.csv'))
# Compact is not needed as everything is already in the DetailedReport

In [50]:
ncaa.drop(columns='Unnamed: 0',inplace=True)
regular.drop(columns='Unnamed: 0',inplace=True)

In [ ]:
# NCAA
# [i for i in data.columns if i.startswith('L')]
winners = ['Season','DayNum','WTeamID','WScore','WLoc','NumOT','WFGM','WFGA','WFGM3','WFGA3','WFTM','WFTA','WOR','WDR','WAst','WTO','WStl','WBlk','WPF','Gender']
losers =  ['Season','DayNum','LTeamID','LScore','WLoc','NumOT','LFGM','LFGA','LFGM3','LFGA3','LFTM','LFTA','LOR','LDR','LAst','LTO','LStl','LBlk','LPF','Gender']

['LTeamID',
 'LScore',
 'LFGM',
 'LFGA',
 'LFGM3',
 'LFGA3',
 'LFTM',
 'LFTA',
 'LOR',
 'LDR',
 'LAst',
 'LTO',
 'LStl',
 'LBlk',
 'LPF']

In [51]:
ncaa.columns

Index(['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore', 'WLoc',
       'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR',
       'WAst', 'WTO', 'WStl', 'WBlk', 'WPF', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3',
       'LFTM', 'LFTA', 'LOR', 'LDR', 'LAst', 'LTO', 'LStl', 'LBlk', 'LPF',
       'Gender'],
      dtype='object')

In [48]:
regular.columns

Index(['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore', 'WLoc',
       'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR',
       'WAst', 'WTO', 'WStl', 'WBlk', 'WPF', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3',
       'LFTM', 'LFTA', 'LOR', 'LDR', 'LAst', 'LTO', 'LStl', 'LBlk', 'LPF',
       'Gender'],
      dtype='object')

In [53]:
massey = pd.read_csv(os.path.join(path,'data','processed','MasseyOrdinals.csv'))

In [54]:
massey

,Unnamed: 0,Season,RankingDayNum,SystemName,TeamID,OrdinalRank,Gender
0,0,2003,35,SEL,1102,159,M
1,1,2003,35,SEL,1103,229,M
2,2,2003,35,SEL,1104,12,M
3,3,2003,35,SEL,1105,314,M
4,4,2003,35,SEL,1106,260,M
...,...,...,...,...,...,...,...
5819223,5819223,2026,114,WOL,1477,282,M
5819224,5819224,2026,114,WOL,1478,292,M
5819225,5819225,2026,114,WOL,1479,307,M
5819226,5819226,2026,114,WOL,1480,286,M
5819227,5819227,2026,114,WOL,1481,308,M