In [100]:
import pandas as pd
import numpy as np
import os
import math

import warnings
warnings.filterwarnings('ignore')

from dotenv import load_dotenv
load_dotenv()

True

In [88]:
dir = os.getenv('DIR')
os.getcwd()
os.chdir(dir)
path = os.getcwd()

In [3]:
# Downloading the data directly from the Kaggle Servers
# kagglehub.competition_download('march-machine-learning-mania-2026')

# Merging CSV Files

In [5]:
os.listdir(os.path.join(path,'data','raw'))

['Cities.csv',
 'Conferences.csv',
 'MConferenceTourneyGames.csv',
 'MGameCities.csv',
 'MMasseyOrdinals.csv',
 'MNCAATourneyCompactResults.csv',
 'MNCAATourneyDetailedResults.csv',
 'MNCAATourneySeedRoundSlots.csv',
 'MNCAATourneySeeds.csv',
 'MNCAATourneySlots.csv',
 'MRegularSeasonCompactResults.csv',
 'MRegularSeasonDetailedResults.csv',
 'MSeasons.csv',
 'MSecondaryTourneyCompactResults.csv',
 'MSecondaryTourneyTeams.csv',
 'MTeamCoaches.csv',
 'MTeamConferences.csv',
 'MTeams.csv',
 'MTeamSpellings.csv',
 'SampleSubmissionStage1.csv',
 'SampleSubmissionStage2.csv',
 'WConferenceTourneyGames.csv',
 'WGameCities.csv',
 'WNCAATourneyCompactResults.csv',
 'WNCAATourneyDetailedResults.csv',
 'WNCAATourneySeeds.csv',
 'WNCAATourneySlots.csv',
 'WRegularSeasonCompactResults.csv',
 'WRegularSeasonDetailedResults.csv',
 'WSeasons.csv',
 'WSecondaryTourneyCompactResults.csv',
 'WSecondaryTourneyTeams.csv',
 'WTeamConferences.csv',
 'WTeams.csv',
 'WTeamSpellings.csv']

## Merging Men and Women Files

In [3]:
# Teams

teams = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MTeams.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WTeams.csv')).assign(Gender='W')
    ]
)

In [4]:

teamconferences = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MTeamConferences.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WTeamConferences.csv')).assign(Gender='W')
    ]
)

In [5]:

ncaatourneyseeds = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MNCAATourneySeeds.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WNCAATourneySeeds.csv')).assign(Gender='W')
    ]
)

In [6]:

secondarytourneyteams = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MSecondaryTourneyTeams.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WSecondaryTourneyTeams.csv')).assign(Gender='W')
    ]
)

In [7]:

secondarytourneycompactresults = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MSecondaryTourneyCompactResults.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WSecondaryTourneyCompactResults.csv')).assign(Gender='W')
    ]
)

In [8]:

ncaatourneycompactresults = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MNCAATourneyCompactResults.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WNCAATourneyCompactResults.csv')).assign(Gender='W')
    ]
)

In [9]:
ncaatourneydetailedresults = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MNCAATourneyDetailedResults.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WNCAATourneyDetailedResults.csv')).assign(Gender='W')
    ]
)

In [10]:
gamecities = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MGameCities.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WGameCities.csv')).assign(Gender='W')
    ]
)

In [11]:
seasons = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MSeasons.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WSeasons.csv')).assign(Gender='W')
    ]
)

In [12]:
conferencetourneygames = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MConferenceTourneyGames.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WConferenceTourneyGames.csv')).assign(Gender='W')
    ]
)

In [13]:

regularseasoncompactresults = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MRegularSeasonCompactResults.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WRegularSeasonCompactResults.csv')).assign(Gender='W')
    ]
)

In [14]:

regularseasondetailedresults = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MRegularSeasonDetailedResults.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WRegularSeasonDetailedResults.csv')).assign(Gender='W')
    ]
)

In [15]:
secondarytourneycompactresults = pd.concat(
    [
    pd.read_csv(os.path.join(path,'data','raw','MSecondaryTourneyCompactResults.csv')).assign(Gender='M'),
    pd.read_csv(os.path.join(path,'data','raw','WSecondaryTourneyCompactResults.csv')).assign(Gender='W')
    ]
)

In [16]:
teams.to_csv(os.path.join(path,'data','processed','Teams.csv'),index=False)
teamconferences.to_csv(os.path.join(path,'data','processed','TeamConfereces.csv'),index=False)
ncaatourneyseeds.to_csv(os.path.join(path,'data','processed','NCAATourneySeeds.csv'),index=False)
secondarytourneyteams.to_csv(os.path.join(path,'data','processed','SecondaryTourneyTeams.csv'),index=False)
ncaatourneycompactresults.to_csv(os.path.join(path,'data','processed','NCAATourneyCompactResults.csv'),index=False)
ncaatourneydetailedresults.to_csv(os.path.join(path,'data','processed','NCAATourneyDetailedResults.csv'),index=False)
gamecities.to_csv(os.path.join(path,'data','processed','GameCities.csv'),index=False)
seasons.to_csv(os.path.join(path,'data','processed','Seasons.csv'),index=False)
conferencetourneygames.to_csv(os.path.join(path,'data','processed','ConferenceTourneyGames.csv'),index=False)
regularseasoncompactresults.to_csv(os.path.join(path,'data','processed','RegularSeasonCompactResults.csv'),index=False)
regularseasondetailedresults.to_csv(os.path.join(path,'data','processed','RegularSeasonDetailedResults.csv'),index=False)
secondarytourneycompactresults.to_csv(os.path.join(path,'data','processed','SecondaryTourneyCompactResults.csv'),index=False)

In [25]:
# Also append the remaining useful files to processed folder to use them for computation

coaches = pd.read_csv(os.path.join(path,'data','raw','MTeamCoaches.csv')).assign(Gender='M')
coaches.to_csv(os.path.join(path,'data','processed','Coaches.csv'))

masseyordinals = pd.read_csv(os.path.join(path,'data','raw','MMasseyOrdinals.csv')).assign(Gender='M')
masseyordinals.to_csv(os.path.join(path,'data','processed','MasseyOrdinals.csv'))

## Merging based on Keys

> Key = Season, Daynum, WTeamID, LTeamID, Gender

* NCAATournamentSessionDetailedResults
* GameCities
* Seasons
* ConferenceTourneyGames
---
* RegularSessionDetailedResults
* GameCities
* Seasons
* ConferenceTourneyGames
---
* SecondaryTourneyCompactResults
* GameCities
* Seasons
* ConferenceTourneyGames

In [ ]:
ncaa = pd.read_csv(os.path.join(path,'data','processed','NCAATourneyDetailedResults.csv'))

regular = pd.read_csv(os.path.join(path,'data','processed','RegularSeasonDetailedResults.csv'))
# cities = pd.read_csv(os.path.join(path,'data','processed','GameCities.csv'))    Not required
# conferencetourneygames = pd.read_csv(os.path.join(path,'data','processed','ConferenceTourneyGames.csv'))

# secondary = pd.read_csv(os.path.join(path,'data','processed','RegularSeasonDetailedResults.csv'))

In [40]:
data = ncaa
data2 = regular

In [ ]:
# NCAA
# data = ncaa.merge(cities,on=['Season','DayNum','WTeamID','LTeamID','Gender'],how='left')
# data = data.merge(conferencetourneygames,on=['Season','DayNum','WTeamID','LTeamID','Gender'],how='left')

In [ ]:
# Regular
# data2 = regular.merge(cities,on=['Season','DayNum','WTeamID','LTeamID','Gender'],how='left')
# data2 = data2.merge(conferencetourneygames,on=['Season','DayNum','WTeamID','LTeamID','Gender'],how='left')

In [42]:
data

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF,Gender
0,2003,134,1421,92,1411,84,N,1,32,69,...,14,31,17,28,16,15,5,0,22,M
1,2003,136,1112,80,1436,51,N,0,31,66,...,7,7,8,26,12,17,10,3,15,M
2,2003,136,1113,84,1272,71,N,0,31,59,...,14,21,20,22,11,12,2,5,18,M
3,2003,136,1141,79,1166,73,N,0,29,53,...,12,17,14,17,20,21,6,6,21,M
4,2003,136,1143,76,1301,74,N,1,27,64,...,15,20,10,26,16,14,5,8,19,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2405,2025,147,3163,78,3425,64,N,0,27,60,...,23,26,13,29,7,15,8,2,18,W
2406,2025,147,3400,58,3395,47,N,0,24,61,...,19,21,11,27,8,21,1,3,14,W
2407,2025,151,3163,85,3417,51,N,0,33,60,...,7,8,8,21,11,19,5,2,12,W
2408,2025,151,3376,74,3400,57,N,0,29,57,...,9,12,9,20,10,14,6,5,17,W
2409,2025,153,3163,82,3376,59,N,0,30,62,...,13,18,17,19,9,11,6,4,17,W

In [43]:
data2

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF,Gender
0,2003,10,1104,68,1328,62,N,0,27,58,...,16,22,10,22,8,18,9,2,20,M
1,2003,10,1272,70,1393,63,N,0,26,62,...,9,20,20,25,7,12,8,6,16,M
2,2003,11,1266,73,1437,61,N,0,24,58,...,14,23,31,22,9,12,2,5,23,M
3,2003,11,1296,56,1457,50,N,0,18,38,...,8,15,17,20,9,19,4,3,23,M
4,2003,11,1400,77,1208,71,N,0,30,61,...,17,27,21,15,12,10,7,1,14,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210799,2026,118,3435,87,3397,77,A,0,35,66,...,9,10,9,20,9,7,2,13,14,W
210800,2026,118,3439,83,3438,82,A,0,27,65,...,18,25,9,22,15,4,3,14,19,W
210801,2026,118,3449,70,3332,69,A,0,27,59,...,13,16,9,20,13,6,2,14,16,W
210802,2026,118,3452,118,3153,60,H,0,42,72,...,14,24,6,19,9,2,1,17,25,W
210803,2026,118,3456,60,3423,41,A,0,22,61,...,7,10,3,19,8,6,5,20,17,W

In [44]:
data.columns

Index(['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore', 'WLoc',
       'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR',
       'WAst', 'WTO', 'WStl', 'WBlk', 'WPF', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3',
       'LFTM', 'LFTA', 'LOR', 'LDR', 'LAst', 'LTO', 'LStl', 'LBlk', 'LPF',
       'Gender'],
      dtype='object')

In [45]:
def ground(row):
    if row['WLoc'] == 'H':
        return 'A'
    elif row['WLoc'] == 'A':
        return 'H'
    else:
        return 'N'
    

data['LLoc'] = data.apply(ground,axis=1)
data2['LLoc'] = data2.apply(ground,axis=1)

In [145]:
# first I will have to separate winners and losers
dataw = data[['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore','WLoc',
       'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR',
       'WAst', 'WTO', 'WStl', 'WBlk', 'WPF','Gender']]

datal = data[['Season', 'DayNum','LTeamID', 'LScore', 'WTeamID', 'WScore','LLoc',
              'NumOT', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3','LFTM', 'LFTA', 'LOR', 'LDR',
              'LAst', 'LTO', 'LStl', 'LBlk', 'LPF','Gender']]

dataw.rename(columns={'WTeamID':'TeamID','LTeamID':'OppTeamID','LScore':'OppScore'},inplace=True)
datal.rename(columns={'LTeamID':'TeamID','WTeamID':'OppTeamID','WScore':'OppScore'},inplace=True)

In [146]:

data2w = data2[['Season', 'DayNum', 'WTeamID', 'WScore','LTeamID', 'LScore', 'WLoc',
       'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR',
       'WAst', 'WTO', 'WStl', 'WBlk', 'WPF','Gender']]

data2l = data2[['Season', 'DayNum','LTeamID', 'LScore', 'WTeamID', 'WScore','LLoc',
              'NumOT', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3','LFTM', 'LFTA', 'LOR', 'LDR',
              'LAst', 'LTO', 'LStl', 'LBlk', 'LPF','Gender']]

data2w.rename(columns={'WTeamID':'TeamID','LTeamID':'OppTeamID','LScore':'OppScore'},inplace=True)
data2l.rename(columns={'WTeamID':'TeamID','LTeamID':'OppTeamID','WScore':'OppScore'},inplace=True)

> Key = TeamID, Seasons, Gender
* NCAATourneySeeds   # No seeds for Secondary and Regular games
* MasseyOrdinals   # Only for Men
* TeamCoaches      # Only for Men
* TeamConferences

In [50]:
ncaatourneyseeds = pd.read_csv(os.path.join(path,'data','processed','NCAATourneySeeds.csv'))
# massey = pd.read_csv(os.path.join(path,'data','processed','MasseyOrdinals.csv'))
teamcoaches = pd.read_csv(os.path.join(path,'data','processed','Coaches.csv'))
teamconferences = pd.read_csv(os.path.join(path,'data','processed','TeamConfereces.csv'))

In [51]:
teamcoaches.columns

Index(['Unnamed: 0', 'Season', 'TeamID', 'FirstDayNum', 'LastDayNum',
       'CoachName', 'Gender'],
      dtype='object')

In [147]:
dataw = dataw.merge(ncaatourneyseeds,on=['Season','TeamID','Gender'],how='left')
# dataw = dataw.merge(massey,on=['Season','TeamID','Gender'],how='left')
dataw = dataw.merge(teamcoaches,on=['Season','TeamID','Gender'],how='left')
dataw = dataw.merge(teamconferences,on=['Season','TeamID','Gender'],how='left')

In [148]:
datal = datal.merge(ncaatourneyseeds,on=['Season','TeamID','Gender'],how='left')
# datal = datal.merge(massey,on=['Season','TeamID','Gender'],how='left')
datal = datal.merge(teamcoaches,on=['Season','TeamID','Gender'],how='left')
datal = datal.merge(teamconferences,on=['Season','TeamID','Gender'],how='left')

In [149]:
# data2w = data2w.merge(massey,on=['Season','TeamID','Gender'],how='left',indicator=True)
data2w = data2w.merge(teamcoaches,on=['Season','TeamID','Gender'],how='left')
data2w = data2w.merge(teamconferences,on=['Season','TeamID','Gender'],how='left')

In [150]:
# data2l = data2l.merge(massey,on=['Season','TeamID','Gender'],how='inner')
data2l = data2l.merge(teamcoaches,on=['Season','TeamID','Gender'],how='left')
data2l = data2l.merge(teamconferences,on=['Season','TeamID','Gender'],how='left')

In [151]:
data2l

,Season,DayNum,OppTeamID,LScore,TeamID,OppScore,LLoc,NumOT,LFGM,LFGA,...,LTO,LStl,LBlk,LPF,Gender,Unnamed: 0,FirstDayNum,LastDayNum,CoachName,ConfAbbrev
0,2003,10,1328,62,1104,68,N,0,22,53,...,18,9,2,20,M,5462.0,0.0,154.0,mark_gottfried,sec
1,2003,10,1393,63,1272,70,N,0,24,67,...,12,8,6,16,M,5616.0,0.0,154.0,john_calipari,cusa
2,2003,11,1437,61,1266,73,N,0,22,73,...,12,2,5,23,M,5610.0,0.0,154.0,tom_crean,cusa
3,2003,11,1457,50,1296,56,N,0,18,49,...,19,4,3,23,M,5638.0,0.0,154.0,rob_judson,mac
4,2003,11,1208,71,1400,77,N,0,24,62,...,10,7,1,14,M,5730.0,0.0,154.0,rick_barnes,big_twelve
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211613,2026,118,3397,77,3435,87,H,0,31,68,...,7,2,13,14,W,NaN,NaN,NaN,NaN,sec
211614,2026,118,3438,82,3439,83,H,0,30,60,...,4,3,14,19,W,NaN,NaN,NaN,NaN,acc
211615,2026,118,3332,69,3449,70,H,0,26,53,...,6,2,14,16,W,NaN,NaN,NaN,NaN,big_ten
211616,2026,118,3153,60,3452,118,A,0,22,53,...,2,1,17,25,W,NaN,NaN,NaN,NaN,big_twelve
211617,2026,118,3423,41,3456,60,H,0,14,48,...,6,5,20,17,W,NaN,NaN,NaN,NaN,caa

In [57]:
data2w

,Season,DayNum,TeamID,WScore,WLoc,NumOT,WFGM,WFGA,WFGM3,WFGA3,...,WTO,WStl,WBlk,WPF,Gender,Unnamed: 0,FirstDayNum,LastDayNum,CoachName,ConfAbbrev
0,2003,10,1104,68,N,0,27,58,3,14,...,23,7,1,22,M,5462.0,0.0,154.0,mark_gottfried,sec
1,2003,10,1272,70,N,0,26,62,8,20,...,13,4,4,18,M,5616.0,0.0,154.0,john_calipari,cusa
2,2003,11,1266,73,N,0,24,58,8,18,...,10,5,2,25,M,5610.0,0.0,154.0,tom_crean,cusa
3,2003,11,1296,56,N,0,18,38,3,9,...,12,14,2,18,M,5638.0,0.0,154.0,rob_judson,mac
4,2003,11,1400,77,N,0,30,61,6,14,...,14,4,4,20,M,5730.0,0.0,154.0,rick_barnes,big_twelve
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211613,2026,118,3435,87,A,0,35,66,11,22,...,5,3,14,14,W,NaN,NaN,NaN,NaN,sec
211614,2026,118,3439,83,A,0,27,65,10,26,...,7,5,9,24,W,NaN,NaN,NaN,NaN,acc
211615,2026,118,3449,70,A,0,27,59,9,27,...,7,2,11,17,W,NaN,NaN,NaN,NaN,big_ten
211616,2026,118,3452,118,H,0,42,72,15,30,...,11,1,4,20,W,NaN,NaN,NaN,NaN,big_twelve
211617,2026,118,3456,60,A,0,22,61,6,18,...,13,4,15,15,W,NaN,NaN,NaN,NaN,caa

In [152]:
print(dataw.columns)
print(datal.columns)
print(data2w.columns)
print(data2l.columns)

Index(['Season', 'DayNum', 'TeamID', 'WScore', 'OppTeamID', 'OppScore', 'WLoc',
       'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR',
       'WAst', 'WTO', 'WStl', 'WBlk', 'WPF', 'Gender', 'Seed', 'Unnamed: 0',
       'FirstDayNum', 'LastDayNum', 'CoachName', 'ConfAbbrev'],
      dtype='object')
Index(['Season', 'DayNum', 'TeamID', 'LScore', 'OppTeamID', 'OppScore', 'LLoc',
       'NumOT', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3', 'LFTM', 'LFTA', 'LOR', 'LDR',
       'LAst', 'LTO', 'LStl', 'LBlk', 'LPF', 'Gender', 'Seed', 'Unnamed: 0',
       'FirstDayNum', 'LastDayNum', 'CoachName', 'ConfAbbrev'],
      dtype='object')
Index(['Season', 'DayNum', 'TeamID', 'WScore', 'OppTeamID', 'OppScore', 'WLoc',
       'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR',
       'WAst', 'WTO', 'WStl', 'WBlk', 'WPF', 'Gender', 'Unnamed: 0',
       'FirstDayNum', 'LastDayNum', 'CoachName', 'ConfAbbrev'],
      dtype='object')
Index(['Season', 'DayNum', 'OppTeamID', 'LScore', 'TeamID', 'OppScore', 'LLoc',
       'NumOT', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3', 'LFTM', 'LFTA', 'LOR', 'LDR',
       'LAst', 'LTO', 'LStl', 'LBlk', 'LPF', 'Gender', 'Unnamed: 0',
       'FirstDayNum', 'LastDayNum', 'CoachName', 'ConfAbbrev'],
      dtype='object')

In [153]:
dataw.drop(columns='Unnamed: 0',inplace=True)
datal.drop(columns='Unnamed: 0',inplace=True)
data2w.drop(columns='Unnamed: 0',inplace=True)
data2l.drop(columns='Unnamed: 0',inplace=True)

In [154]:
dataw['Tournament'] = 'NCAA'
datal['Tournament'] = 'NCAA'
data2w['Tournament'] = 'Regular'
data2l['Tournament'] = 'Regular'

In [155]:
print(dataw.columns)
print(datal.columns)
print(data2w.columns)
print(data2l.columns)

Index(['Season', 'DayNum', 'TeamID', 'WScore', 'OppTeamID', 'OppScore', 'WLoc',
       'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR',
       'WAst', 'WTO', 'WStl', 'WBlk', 'WPF', 'Gender', 'Seed', 'FirstDayNum',
       'LastDayNum', 'CoachName', 'ConfAbbrev', 'Tournament'],
      dtype='object')
Index(['Season', 'DayNum', 'TeamID', 'LScore', 'OppTeamID', 'OppScore', 'LLoc',
       'NumOT', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3', 'LFTM', 'LFTA', 'LOR', 'LDR',
       'LAst', 'LTO', 'LStl', 'LBlk', 'LPF', 'Gender', 'Seed', 'FirstDayNum',
       'LastDayNum', 'CoachName', 'ConfAbbrev', 'Tournament'],
      dtype='object')
Index(['Season', 'DayNum', 'TeamID', 'WScore', 'OppTeamID', 'OppScore', 'WLoc',
       'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR',
       'WAst', 'WTO', 'WStl', 'WBlk', 'WPF', 'Gender', 'FirstDayNum',
       'LastDayNum', 'CoachName', 'ConfAbbrev', 'Tournament'],
      dtype='object')
Index(['Season', 'DayNum', 'OppTeamID', 'LScore', 'TeamID', 'OppScore', 'LLoc',
       'NumOT', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3', 'LFTM', 'LFTA', 'LOR', 'LDR',
       'LAst', 'LTO', 'LStl', 'LBlk', 'LPF', 'Gender', 'FirstDayNum',
       'LastDayNum', 'CoachName', 'ConfAbbrev', 'Tournament'],
      dtype='object')

In [156]:
dataw.rename(columns={
    'WScore':'Score',
    'WLoc':'Loc',
    'WFGM':'FGM',
    'WFGA':'FGA',
    'WFGA3':'FGA3',
    'WFGM3':'FGM3',
    'WFTM':'FTM',
    'WFTA':'FTA',
    'WOR':'OR',
    'WDR':'DR',
    'WAst':'Ast',
    'WTO':'TO',
    'WStl':'Stl',
    'WBlk':'Blk',
    'WPF':'PF',
    },inplace=True)

data2w.rename(columns={
    'WScore':'Score',
    'WLoc':'Loc',
    'WFGM':'FGM',
    'WFGA':'FGA',
    'WFGA3':'FGA3',
    'WFGM3':'FGM3',
    'WFTM':'FTM',
    'WFTA':'FTA',
    'WOR':'OR',
    'WDR':'DR',
    'WAst':'Ast',
    'WTO':'TO',
    'WStl':'Stl',
    'WBlk':'Blk',
    'WPF':'PF',
    },inplace=True)

In [157]:
datal.rename(columns={
    'LScore':'Score',
    'LLoc':'Loc',
    'LFGM':'FGM',
    'LFGA':'FGA',
    'LFGA3':'FGA3',
    'LFGM3':'FGM3',
    'LFTM':'FTM',
    'LFTA':'FTA',
    'LOR':'OR',
    'LDR':'DR',
    'LAst':'Ast',
    'LTO':'TO',
    'LStl':'Stl',
    'LBlk':'Blk',
    'LPF':'PF',
    },inplace=True)

data2l.rename(columns={
    'LScore':'Score',
    'LLoc':'Loc',
    'LFGM':'FGM',
    'LFGA':'FGA',
    'LFGA3':'FGA3',
    'LFGM3':'FGM3',
    'LFTM':'FTM',
    'LFTA':'FTA',
    'LOR':'OR',
    'LDR':'DR',
    'LAst':'Ast',
    'LTO':'TO',
    'LStl':'Stl',
    'LBlk':'Blk',
    'LPF':'PF',
    },inplace=True)

In [158]:
print(dataw.columns)
print(datal.columns)
print(data2w.columns)
print(data2l.columns)

Index(['Season', 'DayNum', 'TeamID', 'Score', 'OppTeamID', 'OppScore', 'Loc',
       'NumOT', 'FGM', 'FGA', 'FGM3', 'FGA3', 'FTM', 'FTA', 'OR', 'DR', 'Ast',
       'TO', 'Stl', 'Blk', 'PF', 'Gender', 'Seed', 'FirstDayNum', 'LastDayNum',
       'CoachName', 'ConfAbbrev', 'Tournament'],
      dtype='object')
Index(['Season', 'DayNum', 'TeamID', 'Score', 'OppTeamID', 'OppScore', 'Loc',
       'NumOT', 'FGM', 'FGA', 'FGM3', 'FGA3', 'FTM', 'FTA', 'OR', 'DR', 'Ast',
       'TO', 'Stl', 'Blk', 'PF', 'Gender', 'Seed', 'FirstDayNum', 'LastDayNum',
       'CoachName', 'ConfAbbrev', 'Tournament'],
      dtype='object')
Index(['Season', 'DayNum', 'TeamID', 'Score', 'OppTeamID', 'OppScore', 'Loc',
       'NumOT', 'FGM', 'FGA', 'FGM3', 'FGA3', 'FTM', 'FTA', 'OR', 'DR', 'Ast',
       'TO', 'Stl', 'Blk', 'PF', 'Gender', 'FirstDayNum', 'LastDayNum',
       'CoachName', 'ConfAbbrev', 'Tournament'],
      dtype='object')
Index(['Season', 'DayNum', 'OppTeamID', 'Score', 'TeamID', 'OppScore', 'Loc',
       'NumOT', 'FGM', 'FGA', 'FGM3', 'FGA3', 'FTM', 'FTA', 'OR', 'DR', 'Ast',
       'TO', 'Stl', 'Blk', 'PF', 'Gender', 'FirstDayNum', 'LastDayNum',
       'CoachName', 'ConfAbbrev', 'Tournament'],
      dtype='object')

In [159]:
final_df = pd.concat([dataw,datal,data2w,data2l],axis=0,ignore_index=True)

In [160]:
final_df.shape

(428068, 28)

In [161]:
final_df.sort_values(by=['Season','DayNum','TeamID'],inplace=True)

In [162]:
final_df.to_csv(os.path.join(path,'data','processed','FData.csv'),index=False)

In [163]:
final_df

,Season,DayNum,TeamID,Score,OppTeamID,OppScore,Loc,NumOT,FGM,FGA,...,Stl,Blk,PF,Gender,Seed,FirstDayNum,LastDayNum,CoachName,ConfAbbrev,Tournament
4832,2003,10,1104,68,1328,62,N,0,27,58,...,7,1,22,M,NaN,0.0,154.0,mark_gottfried,sec,Regular
216450,2003,10,1104,62,1328,68,N,0,22,53,...,9,2,20,M,NaN,0.0,154.0,mark_gottfried,sec,Regular
4833,2003,10,1272,70,1393,63,N,0,26,62,...,4,4,18,M,NaN,0.0,154.0,john_calipari,cusa,Regular
216451,2003,10,1272,63,1393,70,N,0,24,67,...,8,6,16,M,NaN,0.0,154.0,john_calipari,cusa,Regular
4834,2003,11,1266,73,1437,61,N,0,24,58,...,5,2,25,M,NaN,0.0,154.0,tom_crean,cusa,Regular
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
428065,2026,118,3449,69,3332,70,H,0,26,53,...,2,14,16,W,NaN,NaN,NaN,NaN,big_ten,Regular
216448,2026,118,3452,118,3153,60,H,0,42,72,...,1,4,20,W,NaN,NaN,NaN,NaN,big_twelve,Regular
428066,2026,118,3452,60,3153,118,A,0,22,53,...,1,17,25,W,NaN,NaN,NaN,NaN,big_twelve,Regular
216449,2026,118,3456,60,3423,41,A,0,22,61,...,4,15,15,W,NaN,NaN,NaN,NaN,caa,Regular
428067,2026,118,3456,41,3423,60,H,0,14,48,...,5,20,17,W,NaN,NaN,NaN,NaN,caa,Regular

# Feature Engineering

In [164]:
df = pd.read_csv(os.path.join(path,'data','processed','FData.csv'))

In [165]:
df.isnull().sum() # No Null Values

Season              0
DayNum              0
TeamID              0
Score               0
OppTeamID           0
OppScore            0
Loc                 0
NumOT               0
FGM                 0
FGA                 0
FGM3                0
FGA3                0
FTM                 0
FTA                 0
OR                  0
DR                  0
Ast                 0
TO                  0
Stl                 0
Blk                 0
PF                  0
Gender              0
Seed           423236
FirstDayNum    175468
LastDayNum     175468
CoachName      175468
ConfAbbrev          0
Tournament          0
dtype: int64

In [166]:
df['FGA3'] = df['FGA3'] + 0.001
df['FTA'] = df['FTA'] + 0.001

In [167]:

df['FG%'] = df['FGM']/df['FGA']
df['FG%'].apply(lambda x: math.ceil(x * 10000) / 10000)

df['3P%'] = df['FGM3']/df['FGA3']
df['3P%'].apply(lambda x: math.ceil(x * 10000) / 10000)

df['FT%'] = df['FTM']/df['FTA']
df['FT%'].apply(lambda x: math.ceil(x * 10000) / 10000)

0         0.6111
1         0.7273
2         0.5263
3         0.4500
4         0.5862
           ...
428063    0.8125
428064    0.6334
428065    0.5834
428066    0.7143
428067    0.7000
Name: FT%, Length: 428068, dtype: float64

In [168]:
def possesion(row):
    calc = (row['FGA'] - row['OR'] + row['TO']) + (0.44*row['FTA'])
    return calc

In [169]:
df['Possessions'] = df.apply(lambda x: possesion(x),axis=1)

In [170]:
df.columns

Index(['Season', 'DayNum', 'TeamID', 'Score', 'OppTeamID', 'OppScore', 'Loc',
       'NumOT', 'FGM', 'FGA', 'FGM3', 'FGA3', 'FTM', 'FTA', 'OR', 'DR', 'Ast',
       'TO', 'Stl', 'Blk', 'PF', 'Gender', 'Seed', 'FirstDayNum', 'LastDayNum',
       'CoachName', 'ConfAbbrev', 'Tournament', 'FG%', '3P%', 'FT%',
       'Possessions'],
      dtype='object')

## Aggregation

In [177]:
df = df.sort_values(['Season', 'TeamID', 'DayNum'])

In [178]:
df['Win'] = (df['Score'] > df['OppScore']).astype(int)

In [179]:
grouped = df.groupby(['Season', 'TeamID'])

In [180]:
agg_df = grouped.agg({
    'Score': 'mean',
    'FGM': 'mean',
    'FGA': 'mean',
    'FGM3': 'mean',
    'FGA3': 'mean',
    'FTM': 'mean',
    'FTA': 'mean',
    'OR': 'mean',
    'DR': 'mean',
    'Ast': 'mean',
    'TO': 'mean',
    'Stl': 'mean',
    'Blk': 'mean',
    'PF': 'mean',
    'FG%': 'mean',
    '3P%': 'mean',
    'FT%': 'mean',
    'Possessions': 'mean',
    'NumOT': 'mean'
}).reset_index()

In [181]:
agg_df['GamesPlayed'] = grouped.size().values

In [182]:
win_rate = grouped['Win'].mean().reset_index(name='WinRate')

In [183]:
agg_df = agg_df.merge(win_rate, on=['Season', 'TeamID'])

In [185]:
df['RollingScore'] = df.groupby(['Season', 'TeamID'])['Score']\
    .transform(lambda x: x.rolling(10, min_periods=1).mean())

In [186]:
recent = df.groupby(['Season', 'TeamID'])['RollingScore'].last().reset_index()

In [187]:
home = df[df['Loc'] == 'H'].groupby(['Season','TeamID'])['Score'].mean()
away = df[df['Loc'] == 'A'].groupby(['Season','TeamID'])['Score'].mean()

In [ ]:
final_team_df = agg_df.merge(recent, on=['Season','TeamID'], how='left')

In [190]:
final_team_df

,Season,TeamID,Score,FGM,FGA,FGM3,FGA3,FTM,FTA,OR,...,Blk,PF,FG%,3P%,FT%,Possessions,NumOT,GamesPlayed,WinRate,RollingScore
0,2003,1102,60.958333,20.791667,43.333333,7.375000,17.876000,12.000000,17.626000,7.208333,...,1.875000,18.166667,0.486283,0.382230,0.676938,56.505440,0.000000,24,0.500000,61.7
1,2003,1103,83.076923,28.769231,57.692308,5.923077,17.385615,19.615385,27.077923,11.384615,...,2.153846,22.769231,0.500269,0.335175,0.734661,72.491209,0.307692,26,0.500000,75.5
2,2003,1104,67.942857,23.914286,57.771429,6.542857,20.029571,13.571429,19.058143,12.285714,...,3.428571,18.428571,0.415225,0.329065,0.719555,67.785583,0.057143,35,0.485714,71.7
3,2003,1105,72.928571,24.285714,59.714286,6.785714,19.929571,17.571429,24.643857,13.857143,...,3.000000,19.714286,0.405159,0.317901,0.717369,76.700440,0.000000,14,0.500000,72.3
4,2003,1106,63.115385,21.769231,53.923077,4.923077,14.962538,14.653846,22.001000,12.115385,...,3.115385,18.269231,0.404918,0.336481,0.648902,68.295825,0.076923,26,0.500000,63.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14274,2026,3477,64.454545,23.454545,60.590909,6.090909,19.682818,11.454545,15.546455,8.954545,...,6.363636,15.090909,0.389476,0.306290,0.733348,69.022258,0.000000,22,0.500000,60.1
14275,2026,3478,60.500000,20.650000,55.050000,5.500000,19.801000,13.700000,16.951000,9.650000,...,10.650000,16.700000,0.377216,0.284607,0.789353,62.558440,0.100000,20,0.500000,58.2
14276,2026,3479,69.192308,24.615385,56.384615,7.615385,21.885615,12.346154,15.962538,8.307692,...,7.730769,16.653846,0.437259,0.329505,0.772353,66.831209,0.076923,26,0.500000,66.3
14277,2026,3480,70.133333,24.266667,57.600000,7.633333,23.434333,13.966667,20.167667,9.600000,...,5.066667,18.533333,0.424341,0.319599,0.685070,72.440440,0.066667,30,0.500000,69.2
14278,2026,3481,60.100000,22.600000,54.300000,6.100000,18.401000,8.800000,13.301000,9.600000,...,1.400000,13.800000,0.421038,0.319741,0.666939,66.752440,0.000000,10,0.500000,60.1

In [191]:
final_team_df.to_csv(os.path.join(path,'data','final','Dataset.csv'),index=False)