# Packages

In [42]:
import pandas as pd
import numpy as np
import os
import math

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

import warnings
warnings.filterwarnings('ignore')

from dotenv import load_dotenv
load_dotenv()

True

In [2]:
dir = os.getenv('DIR')
os.getcwd()
os.chdir(dir)
path = os.getcwd()

In [3]:
df = pd.read_csv(os.path.join(path,'data','final','Dataset.csv'))

In [4]:
df

,Key,Score,FGM,FGA,FGM3,FGA3,FTM,FTA,OR,DR,...,Blk,PF,FG%,3P%,FT%,Possessions,NumOT,GamesPlayed,WinRate,RollingScore
0,2003-1102,0.883,0.653,0.806,0.473,0.670,0.543,0.629,0.358,0.626,...,0.223,0.648,0.087,0.068,0.108,0.873,0.000,0.732,0.429,0.876
1,2003-1103,0.951,0.725,0.878,0.405,0.617,0.651,0.715,0.517,0.661,...,0.262,0.660,0.087,0.063,0.120,0.926,0.057,0.724,0.482,0.939
2,2003-1104,0.923,0.699,0.882,0.432,0.657,0.600,0.669,0.580,0.698,...,0.344,0.641,0.077,0.062,0.117,0.913,0.008,0.739,0.587,0.926
3,2003-1105,0.931,0.703,0.899,0.467,0.669,0.608,0.680,0.581,0.692,...,0.245,0.664,0.073,0.067,0.117,0.945,0.032,0.716,0.270,0.947
4,2003-1106,0.906,0.694,0.876,0.426,0.636,0.534,0.622,0.562,0.698,...,0.309,0.642,0.077,0.066,0.106,0.918,0.008,0.732,0.465,0.903
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14306,2026-3477,0.901,0.684,0.889,0.427,0.664,0.549,0.612,0.474,0.687,...,0.454,0.610,0.071,0.060,0.121,0.926,0.000,0.716,0.424,0.896
14307,2026-3478,0.877,0.654,0.862,0.432,0.666,0.538,0.587,0.474,0.678,...,0.401,0.609,0.069,0.060,0.124,0.907,0.015,0.739,0.345,0.883
14308,2026-3479,0.908,0.679,0.880,0.510,0.733,0.546,0.603,0.453,0.622,...,0.313,0.638,0.071,0.063,0.122,0.927,0.008,0.732,0.465,0.933
14309,2026-3480,0.929,0.701,0.884,0.479,0.705,0.595,0.668,0.500,0.694,...,0.443,0.627,0.077,0.062,0.116,0.934,0.037,0.724,0.556,0.929
14310,2026-3481,0.879,0.669,0.873,0.390,0.628,0.513,0.577,0.542,0.673,...,0.400,0.616,0.071,0.056,0.121,0.910,0.017,0.716,0.193,0.891

In [20]:
batch_size = 64
teams = 2
d_input = df.shape[1]-1

# Model

In [17]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

## Data

In [19]:
train_df = df[df['Key'].apply(lambda x: int(x.split('-')[0])) <= 2019]
val_df   = df[(df['Key'].apply(lambda x: int(x.split('-')[0])) > 2019) & (df['Key'].apply(lambda x: int(x.split('-')[0])) <= 2022)]
test_df  = df[df['Key'].apply(lambda x: int(x.split('-')[0])) > 2022]

## Components

## Training only the Encoder first

In [11]:
df

,Key,Score,FGM,FGA,FGM3,FGA3,FTM,FTA,OR,DR,...,Blk,PF,FG%,3P%,FT%,Possessions,NumOT,GamesPlayed,WinRate,RollingScore
0,2003-1102,0.883,0.653,0.806,0.473,0.670,0.543,0.629,0.358,0.626,...,0.223,0.648,0.087,0.068,0.108,0.873,0.000,0.732,0.429,0.876
1,2003-1103,0.951,0.725,0.878,0.405,0.617,0.651,0.715,0.517,0.661,...,0.262,0.660,0.087,0.063,0.120,0.926,0.057,0.724,0.482,0.939
2,2003-1104,0.923,0.699,0.882,0.432,0.657,0.600,0.669,0.580,0.698,...,0.344,0.641,0.077,0.062,0.117,0.913,0.008,0.739,0.587,0.926
3,2003-1105,0.931,0.703,0.899,0.467,0.669,0.608,0.680,0.581,0.692,...,0.245,0.664,0.073,0.067,0.117,0.945,0.032,0.716,0.270,0.947
4,2003-1106,0.906,0.694,0.876,0.426,0.636,0.534,0.622,0.562,0.698,...,0.309,0.642,0.077,0.066,0.106,0.918,0.008,0.732,0.465,0.903
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14306,2026-3477,0.901,0.684,0.889,0.427,0.664,0.549,0.612,0.474,0.687,...,0.454,0.610,0.071,0.060,0.121,0.926,0.000,0.716,0.424,0.896
14307,2026-3478,0.877,0.654,0.862,0.432,0.666,0.538,0.587,0.474,0.678,...,0.401,0.609,0.069,0.060,0.124,0.907,0.015,0.739,0.345,0.883
14308,2026-3479,0.908,0.679,0.880,0.510,0.733,0.546,0.603,0.453,0.622,...,0.313,0.638,0.071,0.063,0.122,0.927,0.008,0.732,0.465,0.933
14309,2026-3480,0.929,0.701,0.884,0.479,0.705,0.595,0.668,0.500,0.694,...,0.443,0.627,0.077,0.062,0.116,0.934,0.037,0.724,0.556,0.929
14310,2026-3481,0.879,0.669,0.873,0.390,0.628,0.513,0.577,0.542,0.673,...,0.400,0.616,0.071,0.056,0.121,0.910,0.017,0.716,0.193,0.891

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14311 entries, 2003-1102 to 2026-3481
Data columns (total 22 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Score         14311 non-null  float64
 1   FGM           14311 non-null  float64
 2   FGA           14311 non-null  float64
 3   FGM3          14311 non-null  float64
 4   FGA3          14311 non-null  float64
 5   FTM           14311 non-null  float64
 6   FTA           14311 non-null  float64
 7   OR            14311 non-null  float64
 8   DR            14311 non-null  float64
 9   Ast           14311 non-null  float64
 10  TO            14311 non-null  float64
 11  Stl           14311 non-null  float64
 12  Blk           14311 non-null  float64
 13  PF            14311 non-null  float64
 14  FG%           14311 non-null  float64
 15  3P%           14311 non-null  float64
 16  FT%           14311 non-null  float64
 17  Possessions   14311 non-null  float64
 18  NumOT         14311 non-null  float64
 19  GamesPlayed   14311 non-null  float64
 20  WinRate       14311 non-null  float64
 21  RollingScore  14311 non-null  float64
dtypes: float64(22)
memory usage: 2.5+ MB

In [5]:
keys = df.index.tolist()   # Storing the keys
# keys

In [6]:
df.set_index('Key',inplace=True)

In [7]:
class TeamDataset(Dataset):
    def __init__(self, data):
        self.data = torch.tensor(data.values, dtype=torch.float32)

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]

In [8]:
class TeamEncoder(nn.Module):
    def __init__(self, input_dim, d_model=128, n_heads=4, n_layers=2):
        super().__init__()

        # Project stats → embedding
        self.input_proj = nn.Linear(input_dim, d_model)

        # CLS token
        self.cls = nn.Parameter(torch.randn(1, 1, d_model))

        # Transformer Encoder
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model,
            nhead=n_heads,
            dim_feedforward=256,
            batch_first=True
        )
        self.encoder = nn.TransformerEncoder(encoder_layer, num_layers=n_layers)

        # Decoder (for reconstruction)
        self.decoder = nn.Sequential(
            nn.Linear(d_model, 128),
            nn.ReLU(),
            nn.Linear(128, input_dim)
        )

    def forward(self, x):
        # x: (B, input_dim)

        B = x.size(0)

        x = self.input_proj(x)              # (B, d_model)
        x = x.unsqueeze(1)                 # (B, 1, d_model)

        cls = self.cls.expand(B, 1, -1)    # (B, 1, d_model)

        x = torch.cat([cls, x], dim=1)     # (B, 2, d_model)

        x = self.encoder(x)                # (B, 2, d_model)

        cls_out = x[:, 0, :]               # (B, d_model)

        recon = self.decoder(cls_out)      # (B, input_dim)

        return recon, cls_out

In [39]:
def train_encoder(model, dataloader, epochs=20, lr=1e-3):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    criterion = nn.MSELoss()

    for epoch in range(epochs):
        total_loss = 0

        for batch in dataloader:
            x = batch.to(device)  # (B, input_dim)

            recon, _ = model(x)

            loss = criterion(recon, x)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

In [41]:
teams = TeamDataset(df)
teamsdataloader = torch.utils.data.DataLoader(teams, batch_size=64, shuffle=False)

encoder = TeamEncoder(input_dim=df.shape[1])

train_encoder(encoder, teamsdataloader)

Epoch 1, Loss: 1.4962
Epoch 2, Loss: 0.3321
Epoch 3, Loss: 0.2621
Epoch 4, Loss: 0.2291
Epoch 5, Loss: 0.1842
Epoch 6, Loss: 0.1470
Epoch 7, Loss: 0.1083
Epoch 8, Loss: 0.1008
Epoch 9, Loss: 0.0812
Epoch 10, Loss: 0.0754
Epoch 11, Loss: 0.0736
Epoch 12, Loss: 0.0541
Epoch 13, Loss: 0.0530
Epoch 14, Loss: 0.0629
Epoch 15, Loss: 0.0605
Epoch 16, Loss: 0.0663
Epoch 17, Loss: 0.0610
Epoch 18, Loss: 0.0457
Epoch 19, Loss: 0.0482
Epoch 20, Loss: 0.0499

In [ ]:
class MatchPredictor(nn.Module):
    def __init__(self, encoder, d_model):
        super().__init__()

        self.encoder = encoder

        self.classifier = nn.Sequential(
            nn.Linear(d_model * 4, 128),
            nn.ReLU(),
            nn.Linear(128, 1)
        )

    def forward(self, teamA, teamB):
        _, zA = self.encoder(teamA)   # (B, d)
        _, zB = self.encoder(teamB)

        x = torch.cat([
            zA - zB,
            zA * zB,
            zA,
            zB
        ], dim=-1)

        return torch.sigmoid(self.classifier(x))

## Match pairs making

In [ ]:
matchups = pd.read_csv(os.path.join(path,'data','final','Matchups.csv'))

In [12]:
target = matchups[['Key','Win']]

In [68]:
target.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 428892 entries, 0 to 428891
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Key     428892 non-null  object
 1   Win     428892 non-null  int64
dtypes: int64(1), object(1)
memory usage: 6.5+ MB

In [13]:
target['TeamAID'] = target['Key'].apply(lambda x: x.split('-')[0] + '-' + x.split('-')[1])
target['TeamBID'] = target['Key'].apply(lambda x: x.split('-')[0] + '-' + x.split('-')[2])

In [14]:
target.index

RangeIndex(start=0, stop=428892, step=1)

### Approach 2

In [43]:
encoder.eval()

team_embeddings = {}

with torch.no_grad():
    for team_id, stats in df.iterrows():
        stats = torch.tensor(stats.values, dtype=torch.float32).unsqueeze(0).to(device)

        _, emb = encoder(stats)   # (1, d)

        team_embeddings[team_id] = emb.squeeze(0).cpu()

In [44]:
team_ids = sorted(team_embeddings.keys())

team_embeddings = torch.stack([
    team_embeddings[tid] for tid in team_ids
])

In [45]:
team_ids

['2003-1102',
 '2003-1103',
 '2003-1104',
 '2003-1105',
 '2003-1106',
 '2003-1107',
 '2003-1108',
 '2003-1110',
 '2003-1111',
 '2003-1112',
 '2003-1113',
 '2003-1114',
 '2003-1115',
 '2003-1116',
 '2003-1117',
 '2003-1119',
 '2003-1120',
 '2003-1122',
 '2003-1123',
 '2003-1124',
 '2003-1125',
 '2003-1126',
 '2003-1127',
 '2003-1128',
 '2003-1129',
 '2003-1130',
 '2003-1131',
 '2003-1132',
 '2003-1133',
 '2003-1135',
 '2003-1137',
 '2003-1138',
 '2003-1139',
 '2003-1140',
 '2003-1141',
 '2003-1142',
 '2003-1143',
 '2003-1144',
 '2003-1145',
 '2003-1147',
 '2003-1148',
 '2003-1149',
 '2003-1150',
 '2003-1151',
 '2003-1152',
 '2003-1153',
 '2003-1154',
 '2003-1155',
 '2003-1156',
 '2003-1157',
 '2003-1158',
 '2003-1159',
 '2003-1160',
 '2003-1161',
 '2003-1162',
 '2003-1163',
 '2003-1164',
 '2003-1165',
 '2003-1166',
 '2003-1168',
 '2003-1169',
 '2003-1170',
 '2003-1171',
 '2003-1172',
 '2003-1173',
 '2003-1174',
 '2003-1175',
 '2003-1176',
 '2003-1177',
 '2003-1178',
 '2003-1179',
 '2003-1180',
 '2003-1181',
 '2003-1182',
 '2003-1183',
 '2003-1184',
 '2003-1185',
 '2003-1186',
 '2003-1187',
 '2003-1189',
 '2003-1190',
 '2003-1191',
 '2003-1192',
 '2003-1193',
 '2003-1194',
 '2003-1196',
 '2003-1197',
 '2003-1198',
 '2003-1199',
 '2003-1200',
 '2003-1201',
 '2003-1202',
 '2003-1203',
 '2003-1204',
 '2003-1205',
 '2003-1206',
 '2003-1207',
 '2003-1208',
 '2003-1209',
 '2003-1210',
 '2003-1211',
 '2003-1212',
 '2003-1214',
 '2003-1216',
 '2003-1217',
 '2003-1218',
 '2003-1219',
 '2003-1220',
 '2003-1221',
 '2003-1222',
 '2003-1224',
 '2003-1225',
 '2003-1226',
 '2003-1227',
 '2003-1228',
 '2003-1229',
 '2003-1231',
 '2003-1232',
 '2003-1233',
 '2003-1234',
 '2003-1235',
 '2003-1236',
 '2003-1237',
 '2003-1238',
 '2003-1239',
 '2003-1240',
 '2003-1241',
 '2003-1242',
 '2003-1243',
 '2003-1245',
 '2003-1246',
 '2003-1247',
 '2003-1248',
 '2003-1249',
 '2003-1250',
 '2003-1251',
 '2003-1252',
 '2003-1253',
 '2003-1254',
 '2003-1256',
 '2003-1257',
 '2003-1258',
 '2003-1259',
 '2003-1260',
 '2003-1261',
 '2003-1263',
 '2003-1264',
 '2003-1265',
 '2003-1266',
 '2003-1267',
 '2003-1268',
 '2003-1269',
 '2003-1270',
 '2003-1271',
 '2003-1272',
 '2003-1273',
 '2003-1274',
 '2003-1275',
 '2003-1276',
 '2003-1277',
 '2003-1278',
 '2003-1279',
 '2003-1280',
 '2003-1281',
 '2003-1282',
 '2003-1283',
 '2003-1284',
 '2003-1285',
 '2003-1286',
 '2003-1287',
 '2003-1288',
 '2003-1289',
 '2003-1290',
 '2003-1291',
 '2003-1292',
 '2003-1293',
 '2003-1296',
 '2003-1298',
 '2003-1299',
 '2003-1301',
 '2003-1304',
 '2003-1305',
 '2003-1306',
 '2003-1307',
 '2003-1308',
 '2003-1309',
 '2003-1310',
 '2003-1311',
 '2003-1313',
 '2003-1314',
 '2003-1317',
 '2003-1318',
 '2003-1319',
 '2003-1320',
 '2003-1321',
 '2003-1322',
 '2003-1323',
 '2003-1324',
 '2003-1325',
 '2003-1326',
 '2003-1328',
 '2003-1329',
 '2003-1330',
 '2003-1331',
 '2003-1332',
 '2003-1333',
 '2003-1334',
 '2003-1335',
 '2003-1336',
 '2003-1337',
 '2003-1338',
 '2003-1339',
 '2003-1340',
 '2003-1341',
 '2003-1343',
 '2003-1344',
 '2003-1345',
 '2003-1346',
 '2003-1347',
 '2003-1348',
 '2003-1349',
 '2003-1350',
 '2003-1351',
 '2003-1352',
 '2003-1353',
 '2003-1354',
 '2003-1356',
 '2003-1357',
 '2003-1358',
 '2003-1359',
 '2003-1360',
 '2003-1361',
 '2003-1362',
 '2003-1363',
 '2003-1364',
 '2003-1365',
 '2003-1366',
 '2003-1368',
 '2003-1369',
 '2003-1371',
 '2003-1372',
 '2003-1373',
 '2003-1374',
 '2003-1375',
 '2003-1376',
 '2003-1378',
 '2003-1379',
 '2003-1380',
 '2003-1381',
 '2003-1382',
 '2003-1383',
 '2003-1384',
 '2003-1385',
 '2003-1386',
 '2003-1387',
 '2003-1388',
 '2003-1389',
 '2003-1390',
 '2003-1391',
 '2003-1392',
 '2003-1393',
 '2003-1394',
 '2003-1395',
 '2003-1396',
 '2003-1397',
 '2003-1398',
 '2003-1399',
 '2003-1400',
 '2003-1401',
 '2003-1402',
 '2003-1403',
 '2003-1404',
 '2003-1405',
 '2003-1406',
 '2003-1407',
 '2003-1408',
 '2003-1409',
 '2003-1410',
 '2003-1411',
 '2003-1412',
 '2003-1414',
 '2003-1415',
 '2003-1416',
 '2003-1417',
 '2003-1418',
 '2003-1419',
 '2003-1420',
 '2003-1421',
 '2003-1422',
 '2003-1423',
 '2003-1424',
 '2003-1425',
 '2003-1426',
 '2003-1427',
 '2003-1428',
 '2003-1429',
 '2003-1431',
 '2003-1433',
 '2003-1434',
 '2003-1435',
 '2003-1436',
 '2003-1437',
 '2003-1438',
 '2003-1439',
 '2003-1440',
 '2003-1441',
 '2003-1442',
 '2003-1443',
 '2003-1444',
 '2003-1447',
 '2003-1448',
 '2003-1449',
 '2003-1450',
 '2003-1451',
 '2003-1452',
 '2003-1453',
 '2003-1454',
 '2003-1455',
 '2003-1456',
 '2003-1457',
 '2003-1458',
 '2003-1459',
 '2003-1460',
 '2003-1461',
 '2003-1462',
 '2003-1463',
 '2003-1464',
 '2004-1102',
 '2004-1103',
 '2004-1104',
 '2004-1105',
 '2004-1106',
 '2004-1107',
 '2004-1108',
 '2004-1110',
 '2004-1111',
 '2004-1112',
 '2004-1113',
 '2004-1114',
 '2004-1115',
 '2004-1116',
 '2004-1117',
 '2004-1119',
 '2004-1120',
 '2004-1122',
 '2004-1123',
 '2004-1124',
 '2004-1125',
 '2004-1126',
 '2004-1127',
 '2004-1128',
 '2004-1129',
 '2004-1130',
 '2004-1131',
 '2004-1132',
 '2004-1133',
 '2004-1135',
 '2004-1137',
 '2004-1138',
 '2004-1139',
 '2004-1140',
 '2004-1141',
 '2004-1142',
 '2004-1143',
 '2004-1144',
 '2004-1145',
 '2004-1147',
 '2004-1148',
 '2004-1149',
 '2004-1150',
 '2004-1151',
 '2004-1152',
 '2004-1153',
 '2004-1154',
 '2004-1155',
 '2004-1156',
 '2004-1157',
 '2004-1158',
 '2004-1159',
 '2004-1160',
 '2004-1161',
 '2004-1162',
 '2004-1163',
 '2004-1164',
 '2004-1165',
 '2004-1166',
 '2004-1168',
 '2004-1169',
 '2004-1170',
 '2004-1171',
 '2004-1172',
 '2004-1173',
 '2004-1174',
 '2004-1175',
 '2004-1176',
 '2004-1177',
 '2004-1178',
 '2004-1179',
 '2004-1180',
 '2004-1181',
 '2004-1182',
 '2004-1183',
 '2004-1184',
 '2004-1185',
 '2004-1186',
 '2004-1187',
 '2004-1189',
 '2004-1190',
 '2004-1191',
 '2004-1192',
 '2004-1193',
 '2004-1194',
 '2004-1196',
 '2004-1197',
 '2004-1198',
 '2004-1199',
 '2004-1200',
 '2004-1201',
 '2004-1202',
 '2004-1203',
 '2004-1204',
 '2004-1205',
 '2004-1206',
 '2004-1207',
 '2004-1208',
 '2004-1209',
 '2004-1210',
 '2004-1211',
 '2004-1212',
 '2004-1214',
 '2004-1216',
 '2004-1217',
 '2004-1218',
 '2004-1219',
 '2004-1220',
 '2004-1221',
 '2004-1222',
 '2004-1224',
 '2004-1225',
 '2004-1226',
 '2004-1227',
 '2004-1228',
 '2004-1229',
 '2004-1231',
 '2004-1232',
 '2004-1233',
 '2004-1234',
 '2004-1235',
 '2004-1236',
 '2004-1237',
 '2004-1238',
 '2004-1239',
 '2004-1240',
 '2004-1241',
 '2004-1242',
 '2004-1243',
 '2004-1245',
 '2004-1246',
 '2004-1247',
 '2004-1248',
 '2004-1249',
 '2004-1250',
 '2004-1251',
 '2004-1252',
 '2004-1253',
 '2004-1254',
 '2004-1256',
 '2004-1257',
 '2004-1258',
 '2004-1259',
 '2004-1260',
 '2004-1261',
 '2004-1263',
 '2004-1264',
 '2004-1265',
 '2004-1266',
 '2004-1267',
 '2004-1268',
 '2004-1269',
 '2004-1270',
 '2004-1271',
 '2004-1272',
 '2004-1273',
 '2004-1274',
 '2004-1275',
 '2004-1276',
 '2004-1277',
 '2004-1278',
 '2004-1279',
 '2004-1280',
 '2004-1281',
 '2004-1282',
 '2004-1283',
 '2004-1284',
 '2004-1285',
 '2004-1286',
 '2004-1287',
 '2004-1288',
 '2004-1290',
 '2004-1291',
 '2004-1292',
 '2004-1293',
 '2004-1296',
 '2004-1298',
 '2004-1299',
 '2004-1301',
 '2004-1304',
 '2004-1305',
 '2004-1306',
 '2004-1307',
 '2004-1308',
 '2004-1309',
 '2004-1310',
 '2004-1311',
 '2004-1313',
 '2004-1314',
 '2004-1317',
 '2004-1318',
 '2004-1319',
 '2004-1320',
 '2004-1321',
 '2004-1322',
 '2004-1323',
 '2004-1324',
 '2004-1325',
 '2004-1326',
 '2004-1328',
 '2004-1329',
 '2004-1330',
 '2004-1331',
 '2004-1332',
 '2004-1333',
 '2004-1334',
 '2004-1335',
 '2004-1336',
 '2004-1337',
 '2004-1338',
 '2004-1339',
 '2004-1340',
 '2004-1341',
 '2004-1343',
 '2004-1344',
 '2004-1345',
 '2004-1346',
 '2004-1347',
 '2004-1348',
 '2004-1349',
 '2004-1350',
 '2004-1351',
 '2004-1352',
 '2004-1353',
 '2004-1354',
 '2004-1356',
 '2004-1357',
 '2004-1358',
 '2004-1359',
 '2004-1360',
 '2004-1361',
 '2004-1362',
 '2004-1363',
 '2004-1364',
 '2004-1365',
 '2004-1366',
 '2004-1368',
 '2004-1369',
 '2004-1371',
 '2004-1372',
 '2004-1373',
 '2004-1374',
 '2004-1375',
 '2004-1376',
 '2004-1378',
 '2004-1379',
 '2004-1380',
 '2004-1381',
 '2004-1382',
 '2004-1383',
 '2004-1384',
 '2004-1385',
 '2004-1386',
 '2004-1387',
 '2004-1388',
 '2004-1389',
 '2004-1390',
 '2004-1391',
 '2004-1392',
 '2004-1393',
 '2004-1394',
 '2004-1395',
 '2004-1396',
 '2004-1397',
 '2004-1398',
 '2004-1399',
 '2004-1400',
 '2004-1401',
 '2004-1402',
 '2004-1403',
 '2004-1404',
 '2004-1405',
 '2004-1406',
 '2004-1407',
 '2004-1408',
 '2004-1409',
 '2004-1410',
 '2004-1411',
 '2004-1412',
 '2004-1414',
 '2004-1415',
 '2004-1416',
 '2004-1417',
 '2004-1418',
 '2004-1419',
 '2004-1420',
 '2004-1421',
 '2004-1422',
 '2004-1423',
 '2004-1424',
 '2004-1425',
 '2004-1426',
 '2004-1427',
 '2004-1428',
 '2004-1429',
 '2004-1431',
 '2004-1433',
 '2004-1434',
 '2004-1435',
 '2004-1436',
 '2004-1437',
 '2004-1438',
 '2004-1439',
 '2004-1440',
 '2004-1441',
 '2004-1442',
 '2004-1443',
 '2004-1444',
 '2004-1447',
 '2004-1448',
 '2004-1449',
 '2004-1450',
 '2004-1451',
 '2004-1452',
 '2004-1453',
 '2004-1454',
 '2004-1455',
 '2004-1456',
 '2004-1457',
 '2004-1458',
 '2004-1459',
 '2004-1460',
 '2004-1461',
 '2004-1462',
 '2004-1463',
 '2004-1464',
 '2005-1102',
 '2005-1103',
 '2005-1104',
 '2005-1105',
 '2005-1106',
 '2005-1107',
 '2005-1108',
 '2005-1110',
 '2005-1111',
 '2005-1112',
 '2005-1113',
 '2005-1114',
 '2005-1115',
 '2005-1116',
 '2005-1117',
 '2005-1119',
 '2005-1120',
 '2005-1122',
 '2005-1123',
 '2005-1124',
 '2005-1125',
 '2005-1126',
 '2005-1127',
 '2005-1128',
 '2005-1129',
 '2005-1130',
 '2005-1131',
 '2005-1132',
 '2005-1133',
 '2005-1135',
 '2005-1137',
 '2005-1138',
 '2005-1139',
 '2005-1140',
 '2005-1141',
 '2005-1142',
 '2005-1143',
 '2005-1144',
 '2005-1145',
 '2005-1147',
 '2005-1148',
 '2005-1149',
 '2005-1150',
 '2005-1151',
 '2005-1152',
 '2005-1153',
 '2005-1154',
 '2005-1155',
 '2005-1156',
 '2005-1157',
 '2005-1158',
 '2005-1159',
 '2005-1160',
 '2005-1161',
 '2005-1162',
 '2005-1163',
 '2005-1164',
 '2005-1165',
 '2005-1166',
 '2005-1168',
 '2005-1169',
 '2005-1170',
 '2005-1171',
 '2005-1172',
 '2005-1173',
 '2005-1174',
 '2005-1175',
 '2005-1176',
 '2005-1177',
 '2005-1178',
 '2005-1179',
 '2005-1180',
 '2005-1181',
 '2005-1182',
 '2005-1183',
 '2005-1184',
 '2005-1185',
 '2005-1186',
 '2005-1187',
 '2005-1189',
 '2005-1190',
 '2005-1191',
 '2005-1192',
 '2005-1193',
 '2005-1194',
 '2005-1196',
 '2005-1197',
 '2005-1198',
 '2005-1199',
 '2005-1200',
 '2005-1201',
 '2005-1202',
 '2005-1203',
 '2005-1204',
 '2005-1205',
 '2005-1206',
 '2005-1207',
 '2005-1208',
 '2005-1209',
 '2005-1210',
 '2005-1211',
 '2005-1212',
 '2005-1214',
 '2005-1216',
 '2005-1217',
 '2005-1218',
 '2005-1219',
 '2005-1220',
 '2005-1221',
 '2005-1222',
 '2005-1224',
 '2005-1225',
 '2005-1226',
 '2005-1227',
 '2005-1228',
 '2005-1229',
 '2005-1231',
 '2005-1232',
 '2005-1233',
 '2005-1234',
 '2005-1235',
 '2005-1236',
 '2005-1237',
 '2005-1238',
 '2005-1239',
 '2005-1240',
 '2005-1241',
 '2005-1242',
 '2005-1243',
 '2005-1245',
 '2005-1246',
 '2005-1247',
 '2005-1248',
 '2005-1249',
 '2005-1250',
 '2005-1251',
 '2005-1252',
 '2005-1253',
 '2005-1254',
 '2005-1255',
 '2005-1256',
 '2005-1257',
 '2005-1258',
 '2005-1259',
 '2005-1260',
 '2005-1261',
 '2005-1263',
 '2005-1264',
 '2005-1265',
 '2005-1266',
 '2005-1267',
 '2005-1268',
 '2005-1269',
 '2005-1270',
 '2005-1271',
 '2005-1272',
 '2005-1273',
 '2005-1274',
 '2005-1275',
 '2005-1276',
 '2005-1277',
 '2005-1278',
 '2005-1279',
 '2005-1280',
 '2005-1281',
 '2005-1282',
 '2005-1283',
 '2005-1284',
 '2005-1285',
 '2005-1286',
 '2005-1287',
 '2005-1288',
 '2005-1290',
 '2005-1291',
 '2005-1292',
 '2005-1293',
 '2005-1294',
 '2005-1296',
 '2005-1298',
 '2005-1299',
 '2005-1301',
 '2005-1304',
 '2005-1305',
 '2005-1306',
 '2005-1307',
 '2005-1308',
 '2005-1309',
 '2005-1310',
 '2005-1311',
 '2005-1313',
 '2005-1314',
 '2005-1317',
 '2005-1318',
 '2005-1319',
 '2005-1320',
 '2005-1321',
 '2005-1322',
 '2005-1323',
 '2005-1324',
 '2005-1325',
 '2005-1326',
 '2005-1328',
 '2005-1329',
 '2005-1330',
 '2005-1331',
 '2005-1332',
 '2005-1333',
 '2005-1334',
 '2005-1335',
 '2005-1336',
 '2005-1337',
 '2005-1338',
 '2005-1339',
 '2005-1340',
 '2005-1341',
 '2005-1343',
 '2005-1344',
 '2005-1345',
 '2005-1346',
 '2005-1347',
 '2005-1348',
 '2005-1349',
 '2005-1350',
 '2005-1351',
 '2005-1352',
 '2005-1353',
 '2005-1354',
 '2005-1356',
 '2005-1357',
 '2005-1358',
 '2005-1359',
 '2005-1360',
 '2005-1361',
 '2005-1362',
 '2005-1363',
 '2005-1364',
 '2005-1365',
 '2005-1366',
 '2005-1368',
 '2005-1369',
 '2005-1371',
 '2005-1372',
 '2005-1373',
 '2005-1374',
 '2005-1375',
 '2005-1376',
 '2005-1378',
 '2005-1379',
 '2005-1380',
 '2005-1381',
 '2005-1382',
 '2005-1383',
 '2005-1384',
 '2005-1385',
 '2005-1386',
 '2005-1387',
 '2005-1388',
 '2005-1389',
 '2005-1390',
 '2005-1391',
 '2005-1392',
 '2005-1393',
 '2005-1394',
 '2005-1395',
 '2005-1396',
 '2005-1397',
 '2005-1398',
 '2005-1399',
 '2005-1400',
 '2005-1401',
 '2005-1402',
 '2005-1403',
 '2005-1404',
 '2005-1405',
 '2005-1406',
 '2005-1407',
 '2005-1408',
 '2005-1409',
 '2005-1410',
 '2005-1411',
 '2005-1412',
 '2005-1413',
 '2005-1414',
 '2005-1415',
 '2005-1416',
 '2005-1417',
 '2005-1418',
 '2005-1419',
 '2005-1420',
 '2005-1421',
 '2005-1422',
 '2005-1423',
 '2005-1424',
 '2005-1425',
 '2005-1426',
 '2005-1427',
 '2005-1428',
 '2005-1429',
 '2005-1430',
 '2005-1431',
 '2005-1433',
 '2005-1434',
 '2005-1435',
 '2005-1436',
 '2005-1437',
 '2005-1438',
 '2005-1439',
 '2005-1440',
 '2005-1441',
 '2005-1442',
 '2005-1443',
 '2005-1444',
 '2005-1447',
 '2005-1448',
 '2005-1449',
 '2005-1450',
 '2005-1451',
 '2005-1452',
 '2005-1453',
 '2005-1454',
 '2005-1455',
 '2005-1456',
 '2005-1457',
 '2005-1458',
 '2005-1459',
 '2005-1460',
 '2005-1461',
 '2005-1462',
 '2005-1463',
 '2005-1464',
 '2006-1102',
 '2006-1103',
 '2006-1104',
 '2006-1105',
 '2006-1106',
 '2006-1107',
 '2006-1108',
 '2006-1110',
 '2006-1111',
 '2006-1112',
 '2006-1113',
 '2006-1114',
 '2006-1115',
 '2006-1116',
 '2006-1117',
 '2006-1119',
 '2006-1120',
 ...]

In [46]:
team_embeddings.shape

torch.Size([14311, 128])

In [47]:
target = target[['TeamAID','TeamBID','Win']]

In [48]:
team_embeddings[0]

tensor([-1.1377e-01, -2.8639e-01,  2.4650e-01,  8.5858e-01,  7.4697e-02,
        -5.3307e-02, -1.9253e+00,  1.3090e-01, -1.0276e-01,  3.9500e-01,
         4.1901e-01, -1.5478e-01, -1.1822e-01,  1.3809e+00, -3.3521e-01,
        -4.4488e-01, -4.2639e-01, -1.8628e-01,  1.5618e+00,  3.2168e-03,
         9.4336e-02, -4.1757e+00,  1.0627e-01, -1.5540e-01,  2.0620e-01,
        -4.6126e-02, -2.2289e-01, -2.4052e-02, -2.8870e-01, -9.6145e-02,
        -8.1023e-02, -2.5925e-02, -1.9697e-02, -1.6850e-01,  3.2345e-02,
        -6.6425e-02,  3.3214e-01, -6.0257e+00,  3.7433e-01,  1.1287e-01,
        -2.2679e-01, -5.0447e-01,  5.3854e-03,  6.4771e-01, -7.3023e-02,
         2.3965e-01,  8.6048e-02,  1.3067e-01, -3.0582e-01, -2.8880e-01,
        -6.3703e-01,  2.9371e-02,  1.8857e-01,  1.1952e-01,  4.6658e-01,
         1.8884e-01,  2.5700e-02, -1.1427e-01,  2.1326e-01,  7.5039e-02,
         1.9226e-01, -1.0921e+00,  4.2021e+00,  8.5746e-01,  3.6227e-01,
         4.7019e-04, -5.5777e-01,  3.0646e+00,  1.3156e-01, -2.3311e-01,
        -9.6737e-02, -6.1484e-01,  5.1628e-01,  1.9927e-01, -1.0915e-01,
        -3.7165e-02,  6.4206e-02, -8.3862e-02,  7.4914e-02,  4.9359e-01,
         8.8196e-02,  6.0813e-01,  4.3859e-01, -1.7147e-01,  3.1643e-01,
        -9.7668e-02,  1.9632e-01,  1.6706e-01,  1.2669e-01,  1.2184e-01,
        -1.3929e-01, -3.9517e-01, -1.9146e-01,  1.9027e-01, -4.9927e-02,
         5.6523e-01,  1.3195e-01,  2.2963e-01,  2.2796e-01,  1.2457e-01,
        -2.1453e-01,  7.2105e-02, -1.8525e-01,  6.1683e-02,  1.9894e-01,
         2.5281e-01, -2.0705e-01, -2.3480e-01, -8.4928e-02, -4.1114e-01,
        -7.9566e-01, -3.3853e-01,  3.0592e-01,  7.8901e-02,  2.8688e-01,
        -2.1988e-01, -5.9044e-03, -1.3588e-01, -9.1035e-02,  2.6250e-01,
        -8.7125e-02,  1.0814e-01,  1.6522e+00, -1.5727e-01, -6.9152e-02,
         6.6695e-02, -2.6595e-02, -1.4181e-01])

In [49]:
class MatchDatasetEmb(Dataset):
    def __init__(self, match_data, embedding_matrix):
        """
        match_data: list of (teamA_id, teamB_id, label)
        embedding_matrix: tensor (num_teams, d_model)
        """
        self.matches = match_data
        self.emb = embedding_matrix

    def __len__(self):
        return len(self.matches)

    def __getitem__(self, idx):
        row = self.matches.iloc[idx]
        teamA_id = row["TeamAID"]
        teamB_id = row["TeamBID"]
        label = row["Win"]

        # match team embeddings based on their keys
        teamA = team_ids.index(teamA_id)
        teamB = team_ids.index(teamB_id)

        zA = self.emb[teamA]
        zB = self.emb[teamB]

        return zA, zB, torch.tensor(label, dtype=torch.float32)

In [50]:
class MatchPredictorEmb(nn.Module):
    def __init__(self, d_model):
        super().__init__()

        self.classifier = nn.Sequential(
            nn.Linear(d_model * 4, 128),
            nn.ReLU(),
            nn.Linear(128, 1)
        )

    def forward(self, zA, zB):
        x = torch.cat([
            zA - zB,
            zA * zB,
            zA,
            zB
        ], dim=-1)

        return self.classifier(x)  # logits

In [ ]:
def train_classifier(model, dataloader, epochs=10, lr=1e-3):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    criterion = nn.BCEWithLogitsLoss()

    for epoch in range(epochs):
        model.train()
        total_loss = 0

        for zA, zB, y in dataloader:
            zA = zA.to(device)
            zB = zB.to(device)
            y = y.to(device)

            logits = model(zA, zB).squeeze()
            loss = criterion(logits, y)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        print(f"Epoch {epoch+1}/{epochs} | Loss: {total_loss/len(dataloader):.4f}")

In [30]:
from torch.utils.data import DataLoader

In [51]:
matchups = MatchDatasetEmb(target, team_embeddings)

matchupsdataloader = DataLoader(
    matchups,
    batch_size=64,
    shuffle=True
)

In [52]:
matchups[1]

(tensor([-2.7897e-01, -6.6485e-01, -3.4576e-02,  5.9416e-01,  3.7148e-01,
          1.3864e-01, -2.4226e+00, -1.7819e-01,  2.7734e-01, -3.9808e-02,
          6.9661e-01, -4.1086e-01, -7.4767e-02,  1.3136e+00, -5.7345e-01,
          7.2766e-02,  3.1706e-02,  2.8664e-01,  1.4845e+00, -6.6781e-02,
         -1.4799e-01, -3.9575e+00,  3.6084e-01, -8.8403e-02,  2.1637e-01,
         -2.6603e-01,  2.0518e-01, -3.3468e-02,  1.3487e-01, -7.0101e-02,
          1.4695e-01, -3.0083e-01, -6.1834e-02, -7.4166e-02, -1.5838e-01,
          2.5275e-01,  3.7482e-01, -5.6887e+00, -9.8245e-02, -5.5956e-02,
          1.1529e-01, -2.7704e-01,  1.7861e-01,  5.4600e-01, -1.2522e-01,
         -1.3231e-01, -3.1031e-02,  2.5281e-01, -1.2013e-01,  2.7238e-02,
         -8.9716e-01, -4.6938e-03, -8.4604e-02,  6.2345e-02, -2.9658e-01,
         -1.1372e-01, -4.7444e-01, -1.2512e-01, -1.4758e-01, -1.0260e-01,
         -1.3178e-01, -6.1667e-01,  4.4299e+00,  7.6576e-01,  2.1321e-01,
         -4.9387e-02, -5.0536e-01,  3.4969e+00, -2.2450e-01, -4.9710e-01,
          1.3492e-02,  1.6169e-01,  3.3531e-01, -2.9890e-02,  2.7975e-02,
         -1.9746e-01, -1.1829e-02,  1.4092e-01,  2.9644e-01,  2.3551e-01,
          4.3629e-01,  3.7483e-01,  1.2512e-01,  1.4616e-01,  6.8756e-01,
         -4.9125e-01,  5.7026e-03,  4.3075e-01,  1.8692e-01, -3.4185e-01,
         -5.9817e-02, -7.8005e-02,  9.6798e-02,  2.2693e-01,  2.2835e-02,
         -7.4018e-02,  7.9955e-02,  2.2105e-02, -2.1890e-01, -2.1379e-01,
         -6.7977e-01, -6.1625e-02, -1.1776e-01, -2.2060e-01, -1.9436e-02,
          2.1594e-01,  1.5029e-01, -1.3765e-01,  2.1917e-01,  3.1386e-01,
         -4.7934e-01, -5.9432e-02, -9.6505e-02, -4.2801e-01,  5.5081e-01,
         -3.9107e-01,  1.3663e-01, -1.9849e-02,  1.7207e-01,  4.6580e-01,
          1.1023e-01, -2.0944e-02,  1.6304e+00,  1.2327e-01,  2.3001e-01,
          6.2133e-02,  3.0267e-01,  1.6080e-01]),
 tensor([-0.3858, -0.6247, -0.0122,  0.5331,  0.3912,  0.2138, -2.4798, -0.2234,
          0.4863, -0.0846,  0.8181, -0.3729, -0.0509,  1.3743, -0.5924,  0.1740,
          0.0811,  0.4016,  1.6427,  0.0841, -0.1852, -3.8294,  0.5028,  0.0098,
          0.2754, -0.2830,  0.3222, -0.1780,  0.1252, -0.0210,  0.2572, -0.3221,
          0.0431, -0.0591, -0.3617,  0.2278,  0.4679, -5.5326, -0.0972,  0.1256,
          0.2741, -0.2266,  0.2134,  0.4681, -0.0172, -0.2761, -0.2012,  0.2011,
         -0.1022,  0.0399, -1.0214, -0.2180, -0.1628,  0.0499, -0.4259, -0.1026,
         -0.5991, -0.3094, -0.0154, -0.1813, -0.2361, -0.5564,  4.2140,  0.7510,
          0.2779, -0.0068, -0.5670,  3.5133, -0.2767, -0.5544, -0.0897,  0.1824,
          0.4265, -0.0777, -0.0371, -0.1955,  0.0971,  0.1633,  0.3652,  0.2523,
          0.4608,  0.3854,  0.2649,  0.1703,  0.8033, -0.6491, -0.0636,  0.5023,
          0.1749, -0.3147, -0.2717, -0.1526, -0.0155,  0.1840, -0.0787, -0.2293,
          0.1411,  0.1261, -0.3857, -0.3043, -0.7113,  0.0848, -0.0389, -0.2989,
         -0.2072,  0.0621,  0.1873, -0.0903,  0.2714,  0.4051, -0.5344, -0.0563,
         -0.2046, -0.4514,  0.5812, -0.5384,  0.2515, -0.0450,  0.0647,  0.5614,
          0.1483, -0.1197,  1.7489,  0.3190,  0.2407,  0.0919,  0.2813,  0.1950]),
 tensor(1.))

In [ ]:
d_model = team_embeddings.shape[1]

classifier = MatchPredictorEmb(d_model)

train_classifier(classifier, matchupsdataloader, epochs=10, lr=1e-3)

Epoch 1/10 | Loss: 0.5002
Epoch 2/10 | Loss: 0.4971
Epoch 3/10 | Loss: 0.4963
Epoch 4/10 | Loss: 0.4955
Epoch 5/10 | Loss: 0.4950
Epoch 6/10 | Loss: 0.4946
Epoch 7/10 | Loss: 0.4943
Epoch 8/10 | Loss: 0.4941
Epoch 9/10 | Loss: 0.4940
Epoch 10/10 | Loss: 0.4938

In [35]:
def predict(model, teamA_id, teamB_id, embedding_matrix):
    device = next(model.parameters()).device

    teamA = team_ids.index(teamA_id)
    teamB = team_ids.index(teamB_id)

    
    zA = embedding_matrix[teamA].unsqueeze(0).to(device)
    zB = embedding_matrix[teamB].unsqueeze(0).to(device)

    model.eval()
    with torch.no_grad():
        logits = model(zA, zB)
        prob = torch.sigmoid(logits)

    return prob.item()

In [ ]:
p = predict(classifier, teamA_id='2023-1104', teamB_id='2023-1328', embedding_matrix=team_embeddings)
print("P(A wins):", p)

P(A wins): 0.9383870959281921

### Combining Training Encoder and Model

In [53]:
import torch
import torch.nn as nn

class FullModel(nn.Module):
    def __init__(self, encoder, d_model):
        super().__init__()
        self.encoder = encoder

        self.classifier = nn.Sequential(
            nn.Linear(d_model * 4, 128),
            nn.ReLU(),
            nn.Linear(128, 1)
        )

    def forward(self, teamA, teamB):
        reconA, zA = self.encoder(teamA)
        reconB, zB = self.encoder(teamB)

        x = torch.cat([
            zA - zB,
            zA * zB,
            zA,
            zB
        ], dim=-1)

        logits = self.classifier(x)

        return reconA, reconB, logits

In [54]:
def train_joint(model, dataloader, epochs=10, lr=1e-3, lambda_match=1.0):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    optimizer = torch.optim.Adam(model.parameters(), lr=lr)

    recon_loss_fn = nn.MSELoss()
    match_loss_fn = nn.BCEWithLogitsLoss()

    for epoch in range(epochs):
        model.train()
        total_loss = 0

        for teamA, teamB, y in dataloader:
            teamA = teamA.to(device)
            teamB = teamB.to(device)
            y = y.to(device)

            reconA, reconB, logits = model(teamA, teamB)

            # Reconstruction loss
            loss_recon = recon_loss_fn(reconA, teamA) + recon_loss_fn(reconB, teamB)

            # Match prediction loss
            loss_match = match_loss_fn(logits.squeeze(), y)

            # Combined loss
            loss = loss_recon + lambda_match * loss_match

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        print(f"Epoch {epoch+1} | Loss: {total_loss/len(dataloader):.4f}")

In [55]:
fullmodel = FullModel(encoder,d_model)

In [56]:
train_joint(fullmodel,matchupsdataloader)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (64x128 and 22x128)